### ISSUE TITLE
Found argument '--temp-path' which wasn't expected

### ISSUE THREAD

**Issue by cmacrae** [serokell/deploy-rs#100]
After returning from holiday and updating my inputs, I seem unable to deploy any of my systems due to the following error:
```
error: Found argument '--temp-path' which wasn't expected, or isn't valid in this context

        Did you mean to put '--temp-path' after the subcommand 'activate'?

If you tried to supply `--temp-path` as a PATTERN use `-- --temp-path`

USAGE:
    activate [FLAGS] [OPTIONS] <SUBCOMMAND>

For more information try --help
🚀 ❌ [deploy] [ERROR] Failed to deploy profile: Activating over SSH resulted in a bad exit code: Some(2)
```

I haven't changed anything in my system's configuration or the deployment expression.  
I tried disabling magic rollback, as I understand the temp path is used by this feature, but sadly it didn't help.  

Here's an example of one of my systems and the accompanying common deployment expression:
```nix
{
        nixosConfigurations.compute1 = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          modules = commonComputeConfig ++ [
            ./modules/common.nix
            ./modules/compute.nix
            sops.nixosModules.sops

            {
              compute.id = 1;
              compute.hostId = "ef32e32d";
              compute.efiBlockId = "9B1E-7DE0";
              compute.domain = domain;

              sops.secrets.compute1_store_privatekey.owner = "nix-serve";
            }
          ];
        };

        deploy.nodes = (
          builtins.mapAttrs (
            hostname: attr: {
              inherit hostname;
              fastConnection = true;
              profiles = {
                system = {
                  sshUser = "admin";
                  user = "root";
                  path = deploy-rs.lib."${attr.config.nixpkgs.system}".activate.nixos
                    self.nixosConfigurations."${hostname}";
                };
              };
            }
          ) self.nixosConfigurations
        );

}
```

I'm deploying from an x86_64-darwin machine to x86_64-linux machines.  
In case it's of any help, here's my `deploy-rs` input's state in my `flake.lock`:
```json
"deploy-rs": {
      "inputs": {
        "flake-compat": "flake-compat",
        "naersk": "naersk",
        "nixpkgs": "nixpkgs",
        "utils": "utils"
      },
      "locked": {
        "lastModified": 1625248509,
        "narHash": "sha256-G721I9brAMCkZKXIFsgOQ1JCZ9Rj9DM7QSm0pvpQldc=",
        "owner": "serokell",
        "repo": "deploy-rs",
        "rev": "364ef202e400e4c941e18833ca38fa848ac5a148",
        "type": "github"
      },
      "original": {
        "owner": "serokell",
        "repo": "deploy-rs",
        "type": "github"
      }
    }
```

**Comment by cmacrae** [comment]
Hmm, something seems amiss here. I don't see the presence of a `--targets` flag, which should be there in the version I _thought_ I was running. I'll have a dig around and figure out what I'm doing wrong

**Comment by mkaito** [comment]
That sounds like your flake input and the executable you are running are different versions. Since you say you just updated your inputs, could you try with `nix run github:serokell/deploy-rs` to run a fresh copy of master?

**Comment by cmacrae** [comment]
@mkaito Yep, I think that's exactly what it is 👍 I maintain [a personal binary build](https://github.com/cmacrae/deploy-rs-binary-builds) of deploy-rs, and I had some silly logic in there that only build/pushed to cache when a change in the derivation was observed. I've updated it to also build when serokell/deploy-rs `master` has new commits :)

Thanks for chiming in!

Will be able to try the newly pushed binaries shortly, which I'm sure will solve this issue. So, I'm going to close this
