### ISSUE TITLE
Deploying to other platforms with remote builders?

### ISSUE THREAD

**Issue by antifuchs** [serokell/deploy-rs#11]
I'd love to deploy from my darwin system to a x86_64 linux system (with the aid of #9), which used to work in my previous nixus-based deploy system via remote builders. 

I thought I could use the same builder setup with deploy-rs:

```
$ nix run github:antifuchs/deploy-rs/attempt-to-fix-corefoundation-error -- ./#monitor -- --show-trace --builders 'ssh-ng://linux-box.local x86_64-linux ; ssh-ng://raspi.local aarch64-linux' --builders-use-substitutes
warning: unknown flake output 'config'
warning: unknown flake output 'darwinConfigurations'
warning: unknown flake output 'deploy'
 INFO  deploy > Evaluating flake in ./
 WARN  deploy > The following profiles are going to be deployed:
[monitor.system]
user = "root"
ssh_user = "asf"
path = "/nix/store/rscx6ya03wvd4qj2vv80pz1kazw7whrh-activatable-nixos-system-monitor-21.03.20201121.1ffd7cf"
hostname = "monitor.example.com"
ssh_opts = []

 INFO  deploy::utils::push > Building profile `system` for node `monitor`
error: --- Error ------------------------------------------------------------------------------------------------------ nix
a 'x86_64-linux' with features {} is required to build '/nix/store/91slb8lh1xpqbxx7lhd58hzv4wpmwbh2-builder.pl.drv', but I am a 'x86_64-darwin' with features {benchmark, big-parallel, nixos-test, recursive-nix}
 ERROR deploy              > Failed to push profile: Nix build command resulted in a bad exit code: Some(1)
```

(redacted actual host names).

I think using remote builders ought to work, considering that a previous non-flake-based `nix-build` did use the given builders to build off-platform binaries. Is this a deploy-rs limitation, or is the beta `nix build` program not working right?

**Comment by notgne2** [comment]
At that stage in the process it should just be running `nix build ${repo}#deploy.nodes.${nodeName}.profiles.${profileName}.path`, so I assume it's an issue with newer Nix, you can try with an older Nix version using `flakes-compat`, `deploy-rs` has been set up to handle that

**Comment by antifuchs** [comment]
Thanks for the hint - I just realized that I foolishly forgot to setup nix with distributed build support (need to set both `nix.buildMachines` and `nix.distributedBuilds`). With that set, I got both `nix build` and `deploy` to actually reach out to builder nodes now, so this is plain operator error (:

**Comment by antifuchs** [comment]
That said, I think there might be a regression in newer `nix` - it doesn't support the `--builders` argument in the same way that the previous nix-build did (even though the arg is accepted).
