### ISSUE TITLE
Flake source

### ISSUE THREAD

**Issue by dschrempf** [serokell/deploy-rs#136]
It seems that the source of the deployed flake is not copied to a remote machine. This means, that when using a relative path, for example, like so:

```nix
  systemd.services.myService = {
    # ...
    serviceConfig = { ExecStart = ./path/to/script; };
    # ...
  };
```

The script is unavailable on the remote machine. That is, the deployment succeeds, but silently fails!

However, the script is available on the machine used for deployment because the flake is copied into the local store.

Is this behavior intended?

Thank you!

**Comment by balsoft** [comment]
Yes, this behavior is "intended" for deploy-rs, this is actually a peculiarity of Nix. When you do `toString ./some/path` (which happens inside the NixOS systemd module), it actually gives you a string `./some/path` rather than copying it to store, and then when it eventually does get copied to store that store path is not referenced from the store path that uses it. You should use `"${./some/path}"` instead, like this:
```
  systemd.services.myService = {
    # ...
    serviceConfig = { ExecStart = "${./path/to/script}"; };
    # ...
  };
```

**Comment by dschrempf** [comment]
OK! Thanks a lot for your reply. I guess this is not really related to `deploy-rs` then.

Out of curiousity: Is this the case for all functions using `toString` on a path I am providing? It seems a little disconcerting... Do I have to be careful whenever I directly refer to a path in my flake?

**Comment by balsoft** [comment]
> Do I have to be careful whenever I directly refer to a path in my flake?

Yep. Pretty much any time you want to make sure a certain path gets added to store and referenced properly, you want to do `"${./path}"` and not `./path`.

**Comment by dschrempf** [comment]
Thank you.

**Comment by costowell** [comment]
I just ran into this issue. Could this get documented somewhere like an FAQ or a Common Issues? As a person who was coming from SSHing in, pulling my changes from a repo, and `nixos-rebuild`ing, I assumed that the flake source should always be copied in so I thought this was the fault of the many deploy tools I was trying to get working. Either way I'm glad I found this issue.
