### ISSUE TITLE
Attempting to deploy with ssh auth prompts for remote root password

### ISSUE THREAD

**Issue by efim** [serokell/deploy-rs#140]
Trying to deploy to NixOS vps in Oracle cloud
Previously experimented with morph - successfully

Now attempting to use "deploy-rs" and having trouble with deployment

In config previously tried to only specify `system.user`, 
tried to add my user to trusted nix users on target machine
tried to set sshUser to root
Now I have a deploy config like this:
```
{
  description = "testing out deploy-rs";

  # For accessing `deploy-rs`'s utility Nix functions
  inputs.deploy-rs.url = "github:serokell/deploy-rs";
  inputs.nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

  outputs = { self, nixpkgs, deploy-rs }: {
    nixosConfigurations.pythia-nixos = nixpkgs.lib.nixosSystem {
      system = "aarch64-linux";
      modules = [ ./hosts/cloud/configuration.nix ];
    };

    deploy.magicRollback = true;
    deploy.nodes.pythia.hostname = "<ip>";
    deploy.nodes.pythia.profiles.system = {
        user = "root";
        sshUser = "root";
        path = deploy-rs.lib.x86_64-linux.activate.nixos self.nixosConfigurations.pythia-nixos;
    };

    # This is highly advised, and will prevent many possible mistakes
    checks = builtins.mapAttrs (system: deployLib: deployLib.deployChecks self.deploy) deploy-rs.lib;
  };
}

```

for some reason during deployment I get prompter for the passphrase 5 times in a row, and then I get prompted for passwords for what I assume is target root user (and there is no such password set, I think I only have ssh auth)
```

$ nix run github:serokell/deploy-rs
🚀 ℹ️ [deploy] [INFO] Running checks for flake in .
warning: unknown flake output 'deploy'
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[pythia.system]
user = "root"
ssh_user = "root"
path = "/nix/store/q3d8k4y5dcir1pfclwzinxgysbm66zbc-activatable-nixos-system-instance-20211211-1402-22.05.20211208.581d2d6"
hostname = "130.61.22.28"
ssh_opts = []

🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `pythia`
🚀 ℹ️ [deploy] [INFO] Copying profile `system` to node `pythia`
Enter passphrase for key '/home/efim/.ssh/id_ed25519':
🚀 ℹ️ [deploy] [INFO] Activating profile `system` for node `pythia`
🚀 ℹ️ [deploy] [INFO] Creating activation waiter
Enter passphrase for key '/home/efim/.ssh/id_ed25519':
Enter passphrase for key '/home/efim/.ssh/id_ed25519':
Enter passphrase for key '/home/efim/.ssh/id_ed25519':
Enter passphrase for key '/home/efim/.ssh/id_ed25519':
(root@130.61.22.28) Password:

```

Tried to search through the issues, but couldn't find anything similar.
Is there something I am missing here? Maybe there's something I might try differently for deployment to work?

**Comment by balsoft** [comment]
As for the multiple passphrase requests, I think you should be able to prevent this by using an ssh-agent (which will cache the passphrase for you). Otherwise there's not much we can do (apart from some hacks), we do indeed need to ssh into the target multiple times.

The `(root@130.61.22.28) Password:` is a bit weird, I think your key-based authentication failed. This looks like ssh asking you for the password, not sudo. Are you sure your key is in root's `authorized_keys` on the remote machine?

**Comment by MagicRB** [comment]
This is related to #78 and #107. I think this deserves a meta issue.

A work around for this is to run ssh-agent or something similar. This could be magically handled by deploy-rs in the background, if a agent is not found, run one just for this invocation of deploy-rs.

When it comes to sudo, we'd need bidirectional communication between the `deploy` and `activate` components, which is possible to do through ssh easily. `SUDO_ASKPASS` would be the solution. At that point we could remove most duplicate ssh connections and treat this as a server-client design. The only other ssh connection aside from the primary one we would have to make is the "verify ssh works and you can login" kind.

What do you think @balsoft? If it were up to me I'd start with a clean codebase and pull in bits and pieces as they fit, switching to the server-client design. But rewrites tend to be expensive and its certain we'd break someone's use case.

**Comment by efim** [comment]
@balsoft thank you for mentioning ssh-agent, I've looked into it and will learn to use in the future
As for my ssh key being allowed on remote machine: I'm able to log in via ssh, experiments with deployment via morph succeed, and even in inital error log after first passphrase prompt - there are successful uploads to the target machine, with then following passphrase prompts which are unsuccessful

Currently running `deploy` after adding key to agent I got following error:

```
$ deploy 
🚀 ℹ️ [deploy] [INFO] Running checks for flake in .
warning: unknown flake output 'deploy'
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
🚀 ℹ️ [deploy] [INFO] The following profiles are going to be deployed:
[pythia.system]
user = "root"
ssh_user = "root"
path = "/nix/store/mfg2g3cx7jb6rywwnyc330aj43j8n7y3-activatable-nixos-system-instance-20211211-1402-22.05.20211208.581d2d6"
hostname = "130.61.22.28"
ssh_opts = []

🚀 ℹ️ [deploy] [INFO] Building profile `system` for node `pythia`
🚀 ℹ️ [deploy] [INFO] Copying profile `system` to node `pythia`
🚀 ℹ️ [deploy] [INFO] Activating profile `system` for node `pythia`
🚀 ℹ️ [deploy] [INFO] Creating activation waiter
/nix/store/mfg2g3cx7jb6rywwnyc330aj43j8n7y3-activatable-nixos-system-instance-20211211-1402-22.05.20211208.581d2d6/activate-rs: line 2: /nix/store/yc16rskdr4x6fjdvx099pzi3rdbaijq0-deploy-rs-0.1.0/bin/activate: cannot execute binary file: Exec format error
/nix/store/mfg2g3cx7jb6rywwnyc330aj43j8n7y3-activatable-nixos-system-instance-20211211-1402-22.05.20211208.581d2d6/activate-rs: line 2: /nix/store/yc16rskdr4x6fjdvx099pzi3rdbaijq0-deploy-rs-0.1.0/bin/activate: Success
🚀 ❌ [deploy] [ERROR] Waiting over SSH resulted in a bad exit code: Some(126)
🚀 ℹ️ [deploy] [INFO] Revoking previous deploys
/nix/store/mfg2g3cx7jb6rywwnyc330aj43j8n7y3-activatable-nixos-system-instance-20211211-1402-22.05.20211208.581d2d6/activate-rs: line 2: /nix/store/yc16rskdr4x6fjdvx099pzi3rdbaijq0-deploy-rs-0.1.0/bin/activate: cannot execute binary file: Exec format error
/nix/store/mfg2g3cx7jb6rywwnyc330aj43j8n7y3-activatable-nixos-system-instance-20211211-1402-22.05.20211208.581d2d6/activate-rs: line 2: /nix/store/yc16rskdr4x6fjdvx099pzi3rdbaijq0-deploy-rs-0.1.0/bin/activate: Success
```

Maybe this is related to mismatched machine architectures?

And I went to check - yes, there is a mistake in the expression:
system specifies: `system = "aarch64-linux";`
while path is mismatched:
`path = deploy-rs.lib.x86_64-linux.activate.nixos self.nixosConfigurations.pythia-nixos;`

I tried to do `deploy` with that fixed and seems that `deploy-rs` started to compile - will return to that in the morning

tried to find `deploy-rs` - doesn't seem to be in nixpkgs and couldn't find reference to cachix
is there any distribution of the compiled expressions that I've missed?

**Comment by efim** [comment]
Looks like that was only problem
Now (especially with ssh-agent) things seem to work in incredibly pleasant way

**Comment by balsoft** [comment]
There's no binary cache for deploy-rs (yet), but we're working on it!
