### ISSUE TITLE
Can't run `nix run github:serokell/deploy-rs`

### ISSUE THREAD

**Issue by bbigras** [serokell/deploy-rs#16]
```
❯ nix run github:serokell/deploy-rs                                           nix-shell
error: --- UsageError -------------------------------------------------------------- nix
unrecognised flag '--command'
Try 'nix --help' for more information
```

**Comment by notgne2** [comment]
What Nix (and/or NixOS) version are you using?

**Comment by bbigras** [comment]
Maybe I just have something broken on my system. If I try `nix run` with another project I get:

````
❯ nix run github:edolstra/nix-serve
error: --- UsageError -------------------------------------------------------------- nix
unrecognised flag '--command'
Try 'nix --help' for more information.
```

 - system: `"x86_64-linux"`
 - host os: `Linux 5.7.10-zen1, NixOS, 21.03pre-git (Okapi)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.4pre20201118_79aa7d9`
 - channels(root): `"nixos-21.03pre251123.b839d4a8557"`
 - channels(bbigras): `"home-manager"`
 - nixpkgs: `/run/current-system/nixpkgs`

**Comment by notgne2** [comment]
Well, that's a weird issue for sure, I just updated to the same version and still can't reproduce it on either `deploy-rs` or any other project, even after nuking my eval cache.

**Comment by kirelagin** [comment]
What does `command -V nix` say? Can it be that you forgot that you created some sort of an alias or a shell script call `nix` that dispatches command and rewrites `nix run` to something else?

**Comment by kirelagin** [comment]
Another wild idea: try quoting the argument to `nix run` in case your shell does something funny with the colon.

**Comment by kirelagin** [comment]
Also, what’s this `nix-shell` in your very first listing?

**Comment by bbigras** [comment]
`
❯ command -v nix
/run/current-system/sw/bin/nix
`

> Another wild idea: try quoting the argument to nix run in case your shell does something funny with the colon.

Same thing.

> Also, what’s this nix-shell in your very first listing?

I think it's from my prompt (starship) or fish.

Actually, using bash, the command runs.

**Comment by kirelagin** [comment]
Hm, just to clarify, so when you are running it form `bash`, everything works as expected, right?

Does `command -V nix` in bash point to the same location?

**Comment by balsoft** [comment]
I think I know what's going on here. Something (fish, some plugin, etc) assumes that you're running Nix < 2.4, and because of that it thinks that `nix run` has the old meaning (`nix run` was renamed to `nix shell`, and new `nix run` means running a flake application). `-c/--command` argument only makes sense for the old meaning of `nix run` (so, for the current meaning of `nix shell`), but fish/plugin/whatever doesn't know that and tries to pass something like `--command fish` anyways, which results in that error.

**Comment by kirelagin** [comment]
We all agree that this is certainly not a deploy-rs issue, right?

**Comment by balsoft** [comment]
Yes, that is definitely true.
