### ISSUE TITLE
Option to set local git tag upon deploy

### ISSUE THREAD

**Issue by lilyball** [serokell/deploy-rs#161]
Whenever I deploy a configuration, I would love it if `deploy` could tag the deployed revision with the profile generation on the deployed node. The tag name would be derived from the node and profile names and the newly-activated profile generation.

Example configuration:

```nix
{
  deploy.nodes.pyra = {
    hostname = "<redacted>";
    sshUser = "root";
    fastConnection = true;

    profiles.system = {
      user = "root";
      path = deploy-rs.lib.aarch64-linux.activate.nixos
        self.nixosConfigurations.pyra;
    };
  };
}
```

If I deploy this with a clean repo (i.e. `self.rev` is set) then, upon successful activation of the profile, `deploy` should tag the local revision with a tag like `pyra-system-45` (assuming the new profile generation is 45). This format would ideally be configurable, so I can make it something like `pyra/system-45` or `deploy/pyra-system-45` if I want.

**Comment by PhilTaken** [comment]
This is out of scope for deploy-rs and can be implemented with some simple *sh script I imagine. 

Sorry for the late response :)

**Comment by PhilTaken** [comment]
Ah I see, I have "solved" this by appending the current commit's shortref to the generation name. A sort of after-deployment summary could feasibly be implemented I suppose
