### ISSUE TITLE
Have an officially hosted and/or endorsed binary cache for deploy-rs

### ISSUE THREAD

**Issue by imsofi** [serokell/deploy-rs#163]
Provide a binary cache for deploy-rs, for example trough the use of cachix. I find it strange that everyone using deploy-rs still needs to compile it on their own, or set up their own binary cache for the use with their teams.

There used to be a personal cachix repo for deploy-rs, but it is now unmaintained https://github.com/cmacrae/deploy-rs-binary-builds

@cmacrae do you have any potential advice for creating an official cache?

**Comment by drupol** [comment]
I'm sharing this point of view and hope there will be a binary cache soon... Or better, why not add this tool in nixpkgs ? It would then by default use the official Nixos cache.

**Comment by misuzu** [comment]
https://github.com/NixOS/nixpkgs/pull/182950

**Comment by drupol** [comment]
I think we can now close this thing.

**Comment by imsofi** [comment]
I still think this issue should stay open, as the nixpkgs is not documented as an officially supported method of installing deploy-rs's binaries. While nixpkgs is now a great way to get a binary package of deploy-rs, it is not documented. And i think that is important to get before this issue is closed.

**Comment by teto** [comment]
deploy-rs is a very small project, I see little value for a cache ?

**Comment by wmertens** [comment]
@teto but Rust is huge

**Comment by wmertens** [comment]
So what is the way to use the nixpkgs version? Still use this flake but for the binary use the nixpkgs one?

**Comment by wmertens** [comment]
I found that I can indeed use the flake as library code and but it was importing the flake's deploy-rs instead of using the nixpkgs one.

So I copied the lib.activate code into my own flake and set `final` to be just nixpkgs, removing the overlay entirely.

So perhaps the `lib.activate.*` functions could take an argument to use either the flake's version or nixpkgs' one?

**Comment by teto** [comment]
@wmertens yeah I think I underestimated the build, I install a deploy-rs from the flake and it does take a bit of time to build on CI. So count me interested too now (one can use nixpkgs but I like using software from flakes, makes forking easier)

**Comment by dschrempf** [comment]
I also came across this issue. When using `deploy-rs` from Nixpkgs, and deploying a flake using the `deploy-rs` flake, the executable recompiles, because the flake library code references a different version. The solution of @wmertens works but is a bit cumbersome.

**Comment by imsofi** [comment]
> @wmertens yeah I think I underestimated the build, I install a deploy-rs from the flake and it does take a bit of time to build on CI. So count me interested too now (one can use nixpkgs but I like using software from flakes, makes forking easier)

Yeah i got a intel i3 laptop i usually deploy from, and deploy-rs rebuilds on it take upwards of 15 minutes.

Also, CI runners on GitHub only have 2 cores. So using deploy-rs for CI testing would essentially require a full setup of a binary cache for your project. Which does not track with the project's otherwise simple to use and deploy model.

**Comment by dnaq** [comment]
I’d like to revive this discussion a bit, this becomes extra annoying if deploying to a different target architecture and having to build the `activate` binary using qemu, which takes forever.

Another option might be to separate the derivations for `deploy` and `activate` into two, and maybe even replacing `activate` with a shell script. That would probably alleviate the need for a binary cache.

**Comment by imsofi** [comment]
I have understood a lot of the pain comes from the fact that the exported deploy checks link to `self.packages.${system}.default` over `final.deploy-rs`[^1], so it will always compile the nightly deploy-rs from this repository over another deploy-rs binary.

The simplest thing would likely be to have it point to `final.deploy-rs`, and export an extra overlay to replace the `deploy-rs` package with the nightly in this repo if the end user wants it.

[^1]: https://github.com/serokell/deploy-rs/blob/2a3c5f70eee04a465aa534d8bd4fcc9bb3c4a8ce/flake.nix#L77

**Comment by imsofi** [comment]
For people who want something that works today, I just pushed my reworked deploy-rs lib that uses the `pkgs.deploy-rs` from nixpkgs.[^1] Will probably make a PR down the line when I get more time.

[^1]: https://github.com/imsofi/phenix/commit/cd783955449e299eea7eec45c64126ba5dd82657

**Comment by PhilTaken** [comment]
> I have understood a lot of the pain comes from the fact that the exported deploy checks link to `self.packages.${system}.default` over `final.deploy-rs`[1](#user-content-fn-1-7777a051be8800cba1f096d554028873), so it will always compile the nightly deploy-rs from this repository over another deploy-rs binary.

That is definitely an oversight and should be fixed, thanks!

**Comment by mibmo** [comment]
The PR closing doesn't really address other use cases for a binary cache, namely deploying to a host with a different system (such as deploying _from_ `x86_64-linux` _to_ `aarch64-linux`. I still think a binary cache would be a very big plus and will happily look into making a PR if the maintainers would be open to having it as an option.

**Comment by rvem** [comment]
Fair enough, I agree that it makes sense to provide a cache, perhaps, something cachix-based will do given that they provide decent integration with GitHub Actions

**Comment by mibmo** [comment]
I've set up a cache using cachix at [deploy-rs.cachix.org](https://deploy-rs.cachix.org) ([repo](https://github.com/mibmo/deployrs-binary-cache)) and am working on populating it with CI (a.la [the previous one](https://github.com/cmacrae/deploy-rs-binary-builds)). I've currently got it building `x86_64-linux` and `aarch64-linux`, hoping to get darwin after some more testing (and `riscv64-linux` if deploy-rs supports it?) — FYI: if this project wants the deploy-rs cachix name I'll happily switch to something else.

**Comment by Lcchy** [comment]
FYI in my config I found a way that seems better than the how-to of the README:

```
{
  # ...
  outputs = {
    self,
    nixpkgs,
    deploy-rs,
  }: let
    supportedSystems = ["x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin"];

    # Helper function for generating per-system attributes
    forAllSystems = nixpkgs.lib.genAttrs supportedSystems;

    deployPkgs = forAllSystems (system:
      import nixpkgs {
        inherit system;
        overlays = [
          (self: super: {
            deploy-rs = {
              inherit ((inputs.deploy-rs.overlays.default self super).deploy-rs) lib;
              inherit (super) deploy-rs;
            };
          })
        ];
      });
  in {
    # ...
    deploy.nodes.some-random-system.profiles.system = {
      user = "root";
      # specify the arch of the target device
      path = deployPkgs.aarch64-linux.deploy-rs.lib.activate.nixos self.nixosConfigurations.some-random-system;
    };
  };
}
```

That way there is only a single instance of nixpkgs imported, but above all the binary is fetched from `chache.nixos.org` even for cross-architecture deploys! So it seems there is no need for extra cache? Unless you want the latest version as the nixpkgs one is a bit out of date it seems.

It would be great if the deploy-rs overlay could be changed to something that complies with nixpkgs structure like:
```
deploy-rs = ...derivation...;
lib.deploy-rs = ...lib...;
```

instead of the current nested structure:
```
deploy-rs = {
    deploy-rs = ...derivation...;
    lib = ...lib....;
};
```
which cannot be overlaid onto nixpkgs and still declare the package to be present on the system in the normal way.

I might open an issue about this to see if its possible.
