### ISSUE TITLE
Huge first deployment

### ISSUE THREAD

**Issue by bbigras** [serokell/deploy-rs#17]
I'm currently using nixus and would like to give deploy-rs a try.

I wasn't using flakes before.

One weird thing is that a lot of files seems to be copied for the deployment:

`[2/210/2351 copied (931.2/7020.5 MiB)] copying path '/nix/store/cmrw93jr3a97jdbgqfzv3wi`

I'm surprised since my computer shouldn't be that far behind.

Is that normal? Maybe it's just because I'm starting to use flakes or maybe deploy-rs does something different from nixus.

**Comment by notgne2** [comment]
The use of flakes might mean that the `nixpkgs` in your flake lock is different from your `nixpkgs` channel, but other than that I can't think of any reason this would be

**Comment by notgne2** [comment]
I'm assuming this has been figured out
