### ISSUE TITLE
grub tries to install the bootloader at /dev/xvda even if I set it to "nodev"

### ISSUE THREAD

**Issue by teto** [serokell/deploy-rs#172]
When trying to deploy some node, it fails because grub tries to install itself on /dev/xvda even though /dev/xvda doesn't exist. 
Also i nthe flake I set the filesystem."boot" to "nodev" (which is the good thing to do for efi systems since otherwise it tries to install the legacy/BIOS mode). My "deploy" attribute set in the flake is just a wrapper around my nixosConfigurations, ie., the deployed nix expression should be the same for both. Out of options, I tried to run nixos-rebuild and the deployement worked !

This seems to happen only with deploy-rs; with legacy nixos-rebuild it deployed fine (`nixos-rebuild switch --flake '.#target' --target-host OVH_TARGET --use-remote-sudo`).
I wonder if there is some subtlety that I failed to catch or if deploy-rs adds unconditionnally some nix expressions for some reason ? any idea what could be the reason for this difference between deploy-rs and nixos-rebuild for a same nixosSystem ?

**Comment by MagicRB** [comment]
try adding `--install-bootloader` to nixos-rebuild switch to see whether it fails, im expecting it to fail.

**Comment by teto** [comment]
while writing the answer I think I found the issue in my flake. My "deploy" attrset is a 5 line wrapper around nixosConfiguration but I managed to mess up the code and always link the aws nixosConfiguration even when deploying for ovh. Sry for your time. I will reopen if that's not it but I am pretty sure the issue was on my side. /o\

**Comment by MagicRB** [comment]
Glad you solved it and have a nice day! (Or night :D )
