### ISSUE TITLE
Magic Rollback seems to be preventing deployments

### ISSUE THREAD

**Issue by ykis-0-0** [serokell/deploy-rs#173]
### What did I do
To see if my deployment config works, I was trying to deploy the exactly the running NixOS configuration which the remote is running on *(therefore the deployment should be a no-op and shall not trigger any rollback i guess)*, but it failed.

### Where did the deployment happen
Local: NixOS on WSL2, `x86_64-linux`
Remote: Raspberry Pi 4B, `aarch64-linux`
Configuration to be deployed: https://github.com/ykis-0-0/nixos-config

*The file `secrets.nix` contains passwords that I kept from checking into the repo, It's content resembles the following (with sensitive values `<REPLACED>`):*
<details>
<summary>Contents of `secrets.nix`</summary>

```nix
{
  wifi = {
    "<SOME_SSID_1>" = {
      psk = "<WIFI_PASSWORD_1>";
      authProtocols = [ "WPA-PSK" ];
      priority = 1;
    };

    "<SOME_SSID_2>" = {
      psk = "<WIFI_PASSWORD_2>";
      authProtocols = [ "WPA-PSK" ];
    };
  };

  ddclient_noip = {
    username = "<NO_IP_ACCOUNT>";
    passwordFile = builtins.toFile "ddclient-passwd" "<NO_IP_PASSWORD>";
    domains = [
      # "ykis.ddns.net" # Allocated for minecraft server
      "ykis-host.ddns.net"
    ];
  };
}
```
</details>

### How did it fail

From the console output, it seems that something is wrong while starting `ssh` (the `Invalid argument` line pointed by *the big arrow*), making `deploy-rs` think the wait has ended

<details><summary>A Screenshot since it's more convenient</summary>

*I did **not** input any keystrokes except for the `Enter` to run the `deploy -ds .` line*
![image](https://user-images.githubusercontent.com/64165725/187477563-5886f1d4-497c-46cd-beaa-88c4b613dd30.png)

</details>

### the Question
What should I do to make the Magic Rollback work for my configuration? Thank you very much for helping!

Before filing this issue I've sought help on the Matrix IRC of this repo, I'm attaching the related excerpt of it if it helps.

<details><summary>Another Screenshot</summary>

![image](https://user-images.githubusercontent.com/64165725/187479736-b601ea50-481c-46cb-bc02-434244a0e459.png)

</details>

**Comment by wmertens** [comment]
Not sure what's happening here, but if you have files that aren't checked into the repo, they won't be available during evaluation, since nix copies the repo. So it might be fixed if you use encrypted secrets like with nix-sops
