### ISSUE TITLE
Activate on aach64-linux from x86_64-linux

### ISSUE THREAD

**Issue by dguibert** [serokell/deploy-rs#18]
The `current_exe` used within the remote activation command is taken `std::env:current_exe`.
This assumes that the system on the remote node is the same as the system on the deployment node, which is not when we want to deploy on a raspberry pi from a x86 desktop.

**Comment by kirelagin** [comment]
Sounds like #13.

**Comment by dguibert** [comment]
Yes, you're right.
Might be closed.
