### ISSUE TITLE
assertion '(stdenv).isLinux' failed when running the checks

### ISSUE THREAD

**Issue by Baitinq** [serokell/deploy-rs#180]
```
🚀 ℹ [deploy] [INFO] Running checks for flake in .
error: assertion '(stdenv).isLinux' failed

       at /nix/store/ggmpxvkxg5s63r87075zjvlhyq03qdaa-source/pkgs/os-specific/linux/kernel/generic.nix:71:1:

           70|
           71| assert stdenv.isLinux;
             | ^
           72|
(use '--show-trace' to show detailed location information)
🚀 ❌ [deploy] [ERROR] Failed to check deployment: Nix checking command resulted in a bad exit code: Some(1)
```

My configuration: https://github.com/baitinq/nixos-config

Running NixOS unstable with deploy-rs in the current master branch rev. (deploy-rs follows my nixpkgs input)

If im not running the checks it works fine (I believe).

**Comment by balsoft** [comment]
This is not an issue with `deploy-rs`, but rather your config. Try running `nix flake check` there to reproduce.

**Comment by Baitinq** [comment]
> This is not an issue with `deploy-rs`, but rather your config. Try running `nix flake check` there to reproduce.

My bad, thank you!
