### ISSUE TITLE
Undocumented port options in hostname?

### ISSUE THREAD

**Issue by Stunkymonkey** [serokell/deploy-rs#184]
I am facing some issues with the configuration.
This configuration does not work:
```
{ self, ... }:
{
  user = "root";
  sshUser = "felix";
  sshOpts = [ "-p" "22" "-i" "~/.ssh/keys/local_ed25519" ];
  #sshOpts = [ "-i" "~/.ssh/keys/local_ed25519" ];

  nodes = {
    newton = {
      hostname = "38.242.193.132";
      #hostname = "38.242.193.132:22";
      profiles.system.path =
        deploy-rs.lib."x86_64-linux".activate.nixos
          self.nixosConfigurations."newton";
    };
  };
}
```
it produces:
```
$ deploy .#newton
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
🚀 ❌ [deploy] [ERROR] Failed to resolve target: Deployment data invalid: Cannot creato a socket for '.' from '38.242.193.132': invalid socket address
```

but it the lines which are commented in the config, then it works. I do not see any documentation about defining the port in the hostname. I feel I am doming something unplanned. Any comments? Could be related to #165

PS: the typo `creato` is also something we should fix. I still do not find where it is located.

**Comment by balsoft** [comment]
> I do not see any documentation about defining the port in the hostname.

That's because it's unsupported.

Use `sshOpts = [ "-p" "22" ]` if you want to specify a port.

**Comment by Stunkymonkey** [comment]
If i use `hostname = "38.242.193.132";` in combination with `sshOpts = [ "-p" "22" "-i" "~/.ssh/keys/local_ed25519" ];`, then I am exactly getting the error:
```
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
🚀 ❌ [deploy] [ERROR] Failed to resolve target: Deployment data invalid: Cannot creato a socket for '.' from '38.242.193.132': invalid socket address
```
Any idea why?

**Comment by Stunkymonkey** [comment]
oh nooo. I had the input selected to an old commit, which used an older version. Nevermind...
