### ISSUE TITLE
Depoly-rs with ubuntu falied.

### ISSUE THREAD

**Issue by ZGLinus** [serokell/deploy-rs#195]
I am using NixOS, and I want to using a Ubuntu server to be a node for my NixOS. I had installed nix using single-user installation command from the official website in the Ubuntu server. When i try to run `sudo nix run github:serokell/deploy-rs -- -s . -- --impure` I got an error.
I using `--impure` because I am using a local repository. Here is my flake.nix:
```{nix}
{
  description = "zglinus's NixOS Flake";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
    deploy-rs = {
      url = "github:serokell/deploy-rs";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, ... }@inputs: {
    nixosConfigurations."nixos" = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [
        ./configuration.nix
      ];
    };
    deploy = {
      sshUser = "nix"; 
      user = "root"; 
      autoRollback = false;
      magicRollback = true;
      remoteBuild = false;
      tempPath = /home/nix/.deploy-rs; 
      nodes = {
        "nixos" = {
          hostname = "192.168.123.12";
          profiles.system = {
            path = inputs.deploy-rs.lib.x86_64-linux.activate.nixos self.nixosConfigurations."nixos";
          };
        };
      };
    };
    checks = builtins.mapAttrs (system: deployLib: deployLib.deployChecks self.deploy) inputs.deploy-rs.lib;
  };
} 
```
here is my output
```
🚀 ℹ [deploy] [INFO] Evaluating flake in .
🚀 ℹ [deploy] [INFO] The following profiles are going to be deployed:
[nixos.system]
user = "root"
ssh_user = "nix"
path = "/nix/store/jrwp3kkvfkjd69yc3hjxj7b9v8pwk1kj-activatable-nixos-system-nixos-23.05.20230410.db24d86"
hostname = "192.168.123.12"
ssh_opts = []

🚀 ℹ [deploy] [INFO] Building profile `system` for node `nixos`
🚀 ℹ [deploy] [INFO] Copying profile `system` to node `nixos`
🚀 ℹ [deploy] [INFO] Activating profile `system` for node `nixos`
🚀 ℹ [deploy] [INFO] Creating activation waiter
👀 ℹ [wait] [INFO] Waiting for confirmation event...
⭐ ℹ [activate] [INFO] Activating profile
⭐ ❌ [activate] [ERROR] Failed to execute the command for setting profile: No such file or directory (os error 2)
🚀 ❌ [deploy] [ERROR] Activating over SSH resulted in a bad exit code: Some(1)
🚀 ℹ [deploy] [INFO] Revoking previous deploys
🚀 ❌ [deploy] [ERROR] Deployment failed, rolled back to previous generation

```

**Comment by rvem** [comment]
Could you please provide output with `--debug-logs`?

**Comment by rvem** [comment]
Hmm, `tempPath = /home/nix/.deploy-rs;` is supposed to specify a path to the temporary directory on the target machine since it's used for the `magic-rollback` activation confirmation. Does this directory exist?

**Comment by rvem** [comment]
Hmm, maybe I got confused. Do I understand correctly that your target runs Ubuntu and you want to deploy a profile there?

**Comment by ZGLinus** [comment]
I have a PC running Nixos, and I have a Ubuntu server.
I want my Ubuntu server to be my download node because Ubuntu is easier to use proxies for my  terrible network.
What I want is this: Internet -> proxy -> Ubuntu -> Nixos.

**Comment by rvem** [comment]
Okay, I think I got it.
So `deploy-rs.lib.x86_64-linux.activate.nixos` is supposed to be used to deploy and activate an actual NixOS system on target, which AFAIU won't work as you expect in case of a single-user nix installation on Ubuntu.
Instead, a [`home-manager`](https://github.com/nix-community/home-manager/) configuration will probably suit your needs.

> to be my download node
Also, I don't quite get what did you mean here, do you want to use Ubuntu machine as a remote nix builder?

**Comment by ZGLinus** [comment]
I learn from someboby's blog published in November 2021. It says that this project `deploy-rs` is used to reduce deployment time by parsing the nix configuration file and dowmload the required source also bulid if necessary. And he use a arch PC with nix to be he download machine and depoly the package to his NixOS. 
I copied the `flake.nix` from his blog, and I want to use my Ubuntu to download the package without buliding and deploy them to my NixOS. The `flake.nix` is in my NixOS. Am I doing it right?

**Comment by rvem** [comment]
Could you please link this blog? I have an impression that this person was trying to deploy NixOS from arch, while AFAICS you're trying to approach the reverse approach: deploy nix configuration from NixOS to Ubuntu

**Comment by ZGLinus** [comment]
https://lantian.pub/en/article/modify-website/nixos-initial-config-flake-deploy.lantian/
I'm sorry that I can't make myself clear, because English is not my mother tongue.
When I run nixos-rebulid, nix-build command in my NixOS, because my network environment, the download speed is slow. And I have a ubuntu server in my local area network, I want to use it to increase download speed by using this project and my proxy.

**Comment by ZGLinus** [comment]
emmm, actually I prefer Ubuntu to be a downloader to a builder for my NixOS. Because the Ubuntu runs on a dual-core processor and the NixOS runs on an octa-core processor. 
And when I need to build a package from Github or other websites, NixOS will stop at the fetch step and report an error timeout. I try to make my Ubuntu to be a node to download the package and transmit the package to my NixOS. Because my proxy works well in Ubuntu but not in NixOS.
Is it possible that this project will help me do that?

**Comment by ZGLinus** [comment]
I have tried to run `depoly-rs` switch the role of NixOS and Ubuntu and it succeeded. So I decide to start a NixOS KVM on my Ubuntu server to finish it.

**Comment by ZGLinus** [comment]
I think I make something mistaken. I should edit `flake.nix` in my Ubuntu server, and turn my NixOS as a node. Sorry to waste your time.

**Comment by PhilTaken** [comment]
> I prefer Ubuntu to be a downloader to a builder for my NixOS.

This goes a fair bit beyond the scope of deploy-rs but you could experiment with setting up a downlead proxy on the ubuntu server if that accelerates it at all
