### ISSUE TITLE
Hostname argument override doesn't work for remote build

### ISSUE THREAD

**Issue by notgne2** [serokell/deploy-rs#197]
Looks like it is getting pulled straight from the node data: https://github.com/serokell/deploy-rs/blob/8c9ea9605eed20528bf60fae35a2b613b901fd77/src/push.rs#L164 - instead it should respect `--hostname`

**Comment by notgne2** [comment]
I also don't understand why remote building handles the SSH user in a funny way either, but pushing just can use `data.deploy_defs.ssh_user`

**Comment by rvem** [comment]
> handles the SSH user in a funny way

I'd say that the way the ssh user is handled within `deploy_data` is also somewhat funny. It took me a while to figure out why `data.deploy_defs.ssh_user` is equivalent

**Comment by PhilTaken** [comment]
Ah ya, that one's on me. 
I found the way that arguments and options are handled somewhat untransparent 🤔
