### ISSUE TITLE
Aarch64 cross compilation errors

### ISSUE THREAD

**Issue by Skallwar** [serokell/deploy-rs#200]
I'm trying to deploy some configurations to Aarch64 nodes from an X86_64 node running Linux.

I managed to cross compile my configuration without issued but it failed with the following error:
```
🚀 ℹ️ [deploy] [INFO] Activating profile `system` for node `nixpi`
[sudo] password for pi:
/nix/store/kwic2s1xgzl3j7spjvqsl0xswaa9p2w2-activatable-nixos-system-nixpi-23.05.20230412.fe2ecaf/activate-rs: line 2: /nix/store/5zcrj0jp36ckjbxw5j4nj6b18nzid5rv-deploy-rs-0.1.0/bin/activate: cannot execute binary file: Exec format error
/nix/store/kwic2s1xgzl3j7spjvqsl0xswaa9p2w2-activatable-nixos-system-nixpi-23.05.20230412.fe2ecaf/activate-rs: line 2: /nix/store/5zcrj0jp36ckjbxw5j4nj6b18nzid5rv-deploy-rs-0.1.0/bin/activate: Success
Connection to 192.168.1.251 closed.
```
Here is the corresponding deploy-rs node configuration:
```nix
nixpi = {
    hostname = "192.168.1.251";
    sshUser = "pi";
    sshOpts = ["-t"];
    magicRollback = false; # In order for sshOpts "-t" to work, see https://github.com/serokell/deploy-rs/issues/78#issuecomment-989069609
     profiles.system = {
          user = "root";
          # path = deploy-rs.lib.aarch64-linux.activate.nixos self.nixosConfigurations.nixpi;
         path = deploy-rs.lib.x86_64-linux.activate.nixos self.nixosConfigurations.nixpi;
    };
};
```
As you might notice I'm using "deploy-rs.lib.**x86_64-linux**.activate.nixos self.nixosConfigurations.nixpi". From what I understand while all my configuration has been cross-compiled, the final binary to run `activate` has been compiled native to my builder node so x86_64 instead of aarch64.

When I try to use "deploy-rs.lib.**aarch64-linux**.activate.nixos self.nixosConfigurations.nixpi" I get this error:
```
error: a 'aarch64-linux' with features {} is required to build '/nix/store/c6mljancr1wmnc0vqgwwwi8ic86krix4-builder.pl.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
🚀 ❌ [deploy] [ERROR] Failed to push profile: Nix build command resulted in a bad exit code: Some(1)
```

While I could activate binfmt emulation using `boot.binfmt.emulatedSystems = [ "aarch64-linux" ]` and make this work the build time are atrociously slow to the point where a small config from scratch is taking almost 24h to build.

Is there a way to tell deploy-rs to use `pkgsCross.aarch64-multiplatform` instead?

**Comment by rvem** [comment]
As a temporary workaround, you can try to use `deploy-rs.lib.aarch64-linux.activate.nixos` with `remoteBuild = true` in order to build the entire profile on the target machine

**Comment by Skallwar** [comment]
Thanks for tip. This will work on some of my nodes, but some of them won't as they have less than 1G ram and just dies trying to build something

**Comment by PhilTaken** [comment]
> While I could activate binfmt emulation using `boot.binfmt.emulatedSystems = [ "aarch64-linux" ]` and make this work the build time are atrociously slow to the point where a small config from scratch is taking almost 24h to build.

did you actually try this out? I tried something similar before and I don't remember it taking that long to build. what processor are you running this on?

**Comment by Skallwar** [comment]
Yes I tried. I'm running a i7-1185G7 but it's clocking a bit low (1.2Ghz, I need to take some time to configure [throttled](https://github.com/erpalma/throttled/)). When I have the bare minimum it's okish, around 8h but when I tried to add more stuff (an editor, nginx, ...) it is not manageable, build time explode.

For now I don't have a choice so that's what I'm doing, not updating often and not clearing my nix store. But it is not a solution in my opinion

**Comment by PhilTaken** [comment]
> When I have the bare minimum it's okish, around 8h

do you what it's building? it should pull most stuff from the binary cache

**Comment by notgne2** [comment]
@Skallwar 

> From what I understand while all my configuration has been cross-compiled, the final binary to run activate has been compiled native to my builder node so x86_64 instead of aarch64.

I may be mixed up or there's some issues in the way of it, but I am pretty sure this is not the case. The `activate` functions create an activatable derivation, an activatable derivation is the same as the original, but with the activation script, and `activate` binary included. The `activate` binary is executed on the remote host and manages the activation (stuff like rolling back when unconfirmed), so will need to be native to the target, and doesn't get used at all locally.

**Comment by tennox** [comment]
> As a temporary workaround, you can try to use `deploy-rs.lib.aarch64-linux.activate.nixos` with `remoteBuild = true` in order to build the entire profile on the target machine

Sadly this doesn't work for me - I tried `remoteBuild = true;` and cli flag, but still get:

```
$ deploy --remote-build -d .#raspi-workshop
🚀 ❓ [deploy] [DEBUG] Checking for flake support
🚀 ℹ️ [deploy] [INFO] Running checks for flake in .
error: a 'aarch64-linux' with features {} is required to build '/nix/store/c6mljancr1wmnc0vqgwwwi8ic86krix4-builder.pl.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, ca-derivations, kvm, nixos-test, uid-range}
🚀 ❌ [deploy] [ERROR] Failed to check deployment: Nix checking command resulted in a bad exit code: Some(1)
```

And I don't know how to use binfmt idea as I'm not on NixOS... :cry: 

In case anyone finds a solution, please let me know (I will too :yum: )

**Comment by Skallwar** [comment]
@notgne2 
> The activate binary is executed on the remote host and manages the activation (stuff like rolling back when unconfirmed), so will need to be native to the target, and doesn't get used at all locally.

But the activate binary was built on the host pc not the remote one right? So if my host pc is x86_64 and the remote one is aarch64, the activate binary might be a x86_64 binary trying to run on an aarch64 machine?

**Comment by notgne2** [comment]
`deploy-rs.lib.x86_64-linux.activate.nixos [derivation]` will give you an x86_64 activate binary, `deploy-rs.lib.aarch64-linux.activate.nixos [derivation]` will give you an aarch64 activate binary. There may or may not be errors attempting cross compiling it if you do it the latter way, but activation will fail if you don't.

**Comment by Skallwar** [comment]
I was using this one `deploy-rs.lib.x86_64-linux.activate.nixos` and it failed during activation. 

Anyway, at stated in a previous comment, the error was on my configuration which forced cross compilation. Using `boot.binfmt.emulatedSystems = [ "aarch64-linux" ]` without the 2 lines mentioned work correctly and is fast enough using the cache.

Thanks for your help everyone

**Comment by Skallwar** [comment]
@tennox 

> And I don't know how to use binfmt idea as I'm not on NixOS... 

Your distribution should have a package for this. For example on ubuntu: https://packages.ubuntu.com/bionic/qemu-user-binfmt. Installing this should fix your issue I think

**Comment by mattvaughan** [comment]
Is there a reason `remoteBuild = true` doesn't solve this issue? I understand in some cases you want to build on the deploying machine with qemu, but as @tennox suggests, using remote build still throws an error complaining about the capabilities of the deploying machine.

**Comment by tennox** [comment]
> Is there a reason `remoteBuild = true` doesn't solve this issue? [...] using remote build still throws an error complaining about the capabilities of the deploying machine.

The activation script still needs to be built on the deploying machine, as far as I understand.

**Comment by rvem** [comment]
> using remote build still throws an error complaining about the capabilities of the deploying machine.

Oh, AFAICS, build failure happens during checks build, which indeed needs target system capability for building the profile locally as a part of the check. A solution to this is to provide `--skip-checks` option
