### ISSUE TITLE
nixos-manual-combined.drv failed to validate

### ISSUE THREAD

**Issue by stevenroose** [serokell/deploy-rs#21]
I created some really basic configuration and this happened:

```
$ deploy .
 INFO  deploy > Running checks for flake in .
warning: Git tree 'XXX' is dirty
warning: unknown flake output 'deploy'
warning: unknown flake output 'sshUser'
error: --- Error ----------------------------------------------------------------------------------------------------------------------- nix
builder for '/nix/store/n54gx86pxxlypkybayvdjfrr8zjxa3cj-nixos-manual-combined.drv' failed with exit code 3; last 10 log lines:
  manual-combined.xml:3: element info: Relax-NG validity error : Element book has extra content: info
       1     <?xml version="1.0"?>
       2  <book xmlns="http://docbook.org/ns/docbook" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xi="http://www.w3.org/2001/XInclude" version="5.0" xml:id="book-nixos-manual">
       3     <info>
       4          <title>NixOS Manual</title>
       5    <subtitle>Version 21.03
       6        </subtitle>
       7   </info>
  
  manual-combined.xml fails to validate
error: --- Error ----------------------------------------------------------------------------------------------------------------------- nix
1 dependencies of derivation '/nix/store/hab0rywg9xljxyqsnd4rpg5f7pz8wd3j-nixos-manpages.drv' failed to build
error: --- Error ----------------------------------------------------------------------------------------------------------------------- nix
1 dependencies of derivation '/nix/store/f13in78rbmzwq3zwiw79misya6xykbmd-nixos-manual-html.drv' failed to build
error: --- Error ----------------------------------------------------------------------------------------------------------------------- nix
1 dependencies of derivation '/nix/store/gkkd5a9lpyf4ggndjjwpxbwxfq0zk9rd-system-path.drv' failed to build
error: --- Error ----------------------------------------------------------------------------------------------------------------------- nix
1 dependencies of derivation '/nix/store/pccknb8sn6ay4imgr9d5mhwgkd3s0x4q-nixos-system-XXX-21.03.20201205.118b6d8.drv' failed to build
error: --- Error ----------------------------------------------------------------------------------------------------------------------- nix
1 dependencies of derivation '/nix/store/l24jvvr2kz9zbhnd27982bs9f2krym5v-activatable-nixos-system-XXX-21.03.20201205.118b6d8.drv' failed to build
error: --- Error ----------------------------------------------------------------------------------------------------------------------- nix
1 dependencies of derivation '/nix/store/y0lkh206j9pwh61nfc7wh8xky2ppcisj-deploy-rs-check-activate.drv' failed to build
error: --- Error ----------------------------------------------------------------------------------------------------------------------- nix
build of '/nix/store/2ngx6q2fl6wkaz389xv4l4cdnf72752h-jsonschema-deploy-system.drv', '/nix/store/y0lkh206j9pwh61nfc7wh8xky2ppcisj-deploy-rs-check-activate.drv' failed
 ERROR deploy > Failed to check deployment: Nix checking command resulted in a bad exit code: Some(100)
```

It's hard for me to tell if this is `deploy-rs`'s fault, though. I'm new to using flakes as well.

**Comment by notgne2** [comment]
I'm not sure what your `flake.nix` looks like, but given that there is the output `warning: unknown flake output 'sshUser'` in the logs (this comes from an internal execution of `nix flake check`), I think it may not be formatted correctly. Secondly I don't know much about building of the manual (maybe @balsoft would), but I don't think it's related to `deploy-rs` given this build stage happens _before_ building our deployable payload.

**Comment by balsoft** [comment]
> 1 dependencies of derivation '/nix/store/pccknb8sn6ay4imgr9d5mhwgkd3s0x4q-nixos-system-XXX-21.03.20201205.118b6d8.drv' failed to build

This issue is in fact not deploy-rs related. This was present in some nixpkgs revisions, but shouldn't happen on channels. Make sure you're following a channel (either unstable or 20.09) and try again.

**Comment by stevenroose** [comment]
Yeah I might have messed up some of my channels.

> I'm not sure what your flake.nix looks like, but given that there is the output warning: unknown flake output 'sshUser' in the logs (this comes from an internal execution of nix flake check), I think it may not be formatted correctly.

@notgne2 as for that, the README says I can add the sshUser in any place. I think it logs like that because it's a deploy-rs attribute that nix flake check would not know and this warn about?

Let me retry later with channels fixed.

**Comment by notgne2** [comment]
I must've phrased the README wrong, all the generic options (the ones that can go anywhere) must be at least inside the `deploy` attribute

**Comment by stevenroose** [comment]
Ah yeah for someone not used to flakes, it's a bit confusing. Because you call the "deploy" attribute "top-level", but it's inside outputs in my flake (that's correct, right?).

**Comment by stevenroose** [comment]
This one still persists. I have
```
$ nix-channel --list
nixpkgs https://nixos.org/channels/nixos-20.09
```

**Comment by stevenroose** [comment]
I tried `nix-collect-garbage` and building again, and it gets stuck again on that point. It has to do with the `deploy-rs-check-activate.drv`.

**Comment by balsoft** [comment]
> This one still persists. I have

> $ nix-channel --list

Channels set via `nix-channel` have no effect on flakes. In order to follow a channel in a flake, specify `nixpkgs` input explicitly, something like this:

```nix
{
  inputs.nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";
  outputs = ...;
}
```

However, if you don't need the documentation anyways, disabling it might be ok.

**Comment by notgne2** [comment]
The attribution to `deploy-rs-check-activate` is because this is a derivation that gets built using your deployment's profile as an input, in order to check the details for deployment were correctly included, the trace correctly shows that this build only failed because the NixOS system it depends on fails to build.

**Comment by stevenroose** [comment]
> Channels set via nix-channel have no effect on flakes. In order to follow a channel in a flake, specify nixpkgs input explicitly, something like this:

Ok so this is probably the one piece of information I was missing all yesterday :no_mouth:
