### ISSUE TITLE
Deploying from `x86_64-linux` to `aarch64-linux`

### ISSUE THREAD

**Issue by drupol** [serokell/deploy-rs#219]
Hello,

I would like to deploy updates to my Raspberry router using Deploy-rs. A work-in-progress commit has been made in my config, you can find it [here](https://github.com/drupol/nixos-x260/commit/24eb325239278351f48bdf5fe2b76cad41a1bb8b).

When I run the command: `deploy .#router` (_`router` is my raspberry machine_), it downloaded ~1.2Gb and then, I got this issue.

```
$ deploy .#router
🚀 ℹ [deploy] [INFO] Running checks for flake in .
warning: unknown flake output 'deploy'
🚀 ℹ [deploy] [INFO] Evaluating flake in .
🚀 ℹ [deploy] [INFO] The following profiles are going to be deployed:
[router.system]
user = "root"
ssh_user = "pol"
path = "/nix/store/xlz3rd2dfkya33rjr1q6l1j849mh4lyw-activatable-nixos-system-router-23.11.20230607.381e92a"
hostname = "router"
ssh_opts = []

🚀 ℹ [deploy] [INFO] Building profile `system` for node `router`
error: a 'aarch64-linux' with features {} is required to build '/nix/store/c6mljancr1wmnc0vqgwwwi8ic86krix4-builder.pl.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
🚀 ❌ [deploy] [ERROR] Failed to push profile: Nix build command resulted in a bad exit code: Some(1)
```

Could you please help me by telling me if the `deploy-rs` has been correctly done (based on the [commit](https://github.com/drupol/nixos-x260/commit/24eb325239278351f48bdf5fe2b76cad41a1bb8b)) and if you have a solution on the issue I currently have ?

Thanks in advance.

**Comment by rvem** [comment]
Hi! Looks similar to https://github.com/serokell/deploy-rs/issues/200.
Currently, there are two solutions: either enable aarch64 cross-compilation on a machine you're deploying from (by setting `boot.binfmt.emulatedSystems = [ "aarch64-linux" ]`), or using `remoteBuild = true;` in case your target machine is powerful enough

**Comment by drupol** [comment]
Thanks!

**Comment by ryan4yin** [comment]
@rvem Can we use crossSystem(instead of emulatedSystems) here?

**Comment by tcurdt** [comment]
Anyone got a working example on how to do cross builds and deploys?
I am looking for all combination of:

**Host**:
x86_64-linux
aarch64-darwin

**Target**:
aarch64-linux
x86_64-linux

**Comment by ryan4yin** [comment]
@tcurdt The solution I found is switch to [colmena](https://github.com/zhaofengli/colmena), which supports custom `nixpkgs` instance by its `meta.nixpkgs` & `meta.nodeNixpkgs` parameters.
