### ISSUE TITLE
`--profile-user` error

### ISSUE THREAD

**Issue by ilyakooo0** [serokell/deploy-rs#235]
I recently started getting this error:

```
error: Found argument '--profile-user' which wasn't expected, or isn't valid in this context
```

**Comment by rvem** [comment]
Please check https://github.com/serokell/deploy-rs/issues/232

**Comment by ilyakooo0** [comment]
I do not understand what the workaround is. I pull deploy-rs from the master branch and it still doesn't work.

**Comment by rvem** [comment]
`nix flake lock --update-input deploy-rs` should do the thing

**Comment by ilyakooo0** [comment]
![image](https://github.com/serokell/deploy-rs/assets/6209627/f11f9e28-27b6-4825-9bd4-8e929ba4ae89)

**Comment by ilyakooo0** [comment]
Thanks (:

**Comment by rvem** [comment]
Did you resolve your problem?
If so, can we close the issue?:)
