### ISSUE TITLE
How to prepare target machines?

### ISSUE THREAD

**Issue by stevenroose** [serokell/deploy-rs#24]
This is the first time I'm using a deploy tool to setup NixOS machines. I have only used regular NixOS machines manually by pushing configurations into them and updating.

So now for testing I have a VirtualBox VM that I have installed NixOS onto and I'd like to use deploy-rs to deploy onto the machine (in order to later deploy onto a real VPS).

Is there a standard way of "preparing" a machine to be a target for a deployment like with deploy-rs?

**Comment by notgne2** [comment]
`deploy-rs` is abstract and the target node does not need any preperation, though it's likely you're talking about using it to deploy a NixOS system profile, in this case as long as the system is already running NixOS, there is absolutely nothing to do and it should work as long as the machine deploying has ssh access to your target server.

**Comment by stevenroose** [comment]
Hmm, so how does it work with `hardware-configuration.nix`? Does it mean that a deploy-rs "node" needs to have its `hardware-configuration.nix` packages inside? So that you can't deploy a node to two different machines?

**Comment by notgne2** [comment]
You will need to include what would be in `hardware-configuration.nix` in the configuration you deploy using deploy-rs, the easiest way is probably to use `nixos-generate-config` and copy the configuration it generates

**Comment by stevenroose** [comment]
Hmm, so what is the strategy to deploy the same config to multiple machines? Defining them as multiple nodes and having a config that imports a `-common` config? K that makes sense. Thanks :) Very excited about this!
