### ISSUE TITLE
Parallelize (only) build stage when remote build is used

### ISSUE THREAD

**Issue by ykis-0-0** [serokell/deploy-rs#243]
Since we now have the option `remoteBuild`, I think it would be rather feasible to parallelize the build of the profiles on hosts.

It may be better to keep activation serial, however for building the profiles, since doesn't cause any dependency issues, I suppose it'll beneficial to parallelize the builds when built on remote hosts.

**Comment by rvem** [comment]
This idea was expressed already in https://github.com/serokell/deploy-rs/issues/46#issuecomment-1712552174 :)
I agree that it'd be useful to have. Perhaps, we'll get to it eventually, but sadly I can't give any estimates at the moment

**Comment by ykis-0-0** [comment]
Oh, sorry for raising the redundant issue, I shall close this in favor for the more general discussion
