### ISSUE TITLE
question: how to ensure non-0 exit code of rolled back deployment?

### ISSUE THREAD

**Issue by hlolli** [serokell/deploy-rs#245]
I'm using deploy-rs personally and at work, and this has been a longstanding issue for a long time, that we falsly believe that we have new deployments in production, only to expand the CI pipeline logs to see that the deployment didn't success, but "successfully" rolled back. This is giving us bad signals about the state of our system. Is there a command line flag or something that I'm missing out on, that ensures that any non-passing deployment is always, under all circumstances, returning non-0 exit code?

**Comment by rvem** [comment]
Hmm, rollback is supposed to return non-zero exit code (see https://github.com/serokell/deploy-rs/pull/181).
If this is not the case, this indeed sounds like a thing to investigate

**Comment by rvem** [comment]
Can you provide the `deploy-rs` revision you're using and logs that unexpectedly have zero exit-code?

**Comment by hlolli** [comment]
```
      "locked": {
        "lastModified": 1698921442,
        "narHash": "sha256-7KmvhQ7FuXlT/wG4zjTssap6maVqeAMBdtel+VjClSM=",
        "owner": "serokell",
        "repo": "deploy-rs",
        "rev": "660180bbbeae7d60dad5a92b30858306945fd427",
        "type": "github"
      },
      "original": {
        "owner": "serokell",
        "repo": "deploy-rs",
        "type": "github"
      }
  ```
  
  
![deployrs](https://github.com/serokell/deploy-rs/assets/6074754/b45d4e90-8335-4bf4-8b07-ac82fae7334c)

**Comment by rvem** [comment]
Thanks, I'll investigate

**Comment by hlolli** [comment]
thanks 🙏 !

**Comment by rvem** [comment]
Let me know if you encounter any other unexpected non-zero exit code occurrences :sweat_smile:
