### ISSUE TITLE
overlays flake output change requires update to README

### ISSUE THREAD

**Issue by sedlund** [serokell/deploy-rs#267]
https://github.com/serokell/deploy-rs/blob/2bad21828ee2c5d1e42588d5f4c53f5b10300c6a/README.md?plain=1#L102

This example is no longer working with master due to changing flake outputs from a92835264100583903dc408abe43d461ff7d4dca

@Sereja313

**Comment by clamydo** [comment]
Should probably just changed to `deploy-rs.overlays.default`.

**Comment by Sereja313** [comment]
Oh, thanks for noticing!
