### ISSUE TITLE
Failed to evaluate deployment data

### ISSUE THREAD

**Issue by RyanGibb** [serokell/deploy-rs#270]
I'm getting `Failed to evaluate deployment data: Error decoding the JSON from evaluation: invalid type: sequence, expected a map at line 1 column 9` when deploying the configuration at https://github.com/RyanGibb/nixos/blob/2fe1e6cbed66f52c2932364a9890902867043480/flake.nix#L189-L213

**Comment by PhilTaken** [comment]
`builtins.map` returns a list when a map is expected. you probably want to look at https://noogle.dev/f/builtins/listToAttrs

**Comment by RyanGibb** [comment]
Thanks! It's fixed at https://github.com/RyanGibb/nixos/blob/76c807b1e53336b21c47b8a53f832cb843345186/flake.nix#L189-L226
