### ISSUE TITLE
Home-manager profile example?

### ISSUE THREAD

**Issue by starptr** [serokell/deploy-rs#284]
I'm a little confused on using deploy-rs for pushing a profile based on home-manager. The Readme mentions [you can use home-manager on any non-privileged user](https://github.com/serokell/deploy-rs#profile) but doesn't explain how. Reading the source, I got the vague idea that you're [supposed to use the home-manager function](https://github.com/serokell/deploy-rs/blob/3867348fa92bc892eba5d9ddb2d7a97b9e127a8a/flake.nix#L116) but I'm not sure how to use it. Any pointers appreciated :)

**Comment by sedlund** [comment]
add another profile configuration for the home-manager profile

```nix
deploy.nodes.some-random-system = {
        hostname = "some-random-system";
        profiles.system = {
          user = "root";
          path = deploy-rs.lib.x86_64-linux.activate.nixos self.nixosConfigurations.some-random-system;
        };
        profiles.userhome = {
          user = "myuser"
          path = deploy-rs.lib.x86_64-linux.activate.home-manager self.homeConfigurations.x86_64-linux.myuser;
    };

```
the above assumes the homeConfigurations is defined in that flake.

you can see how i do it here where my home-manager is in a separate flake:

https://codeberg.org/Displace4490/sgp1/src/commit/2e3ed8c905af31c86008b0cf146da98dcadb45fc/flake.nix#L172

**Comment by starptr** [comment]
Thanks! I did a bit of variable chasing and tl;dr/for posterity, `deploy-rs.lib.x86_64-linux.activate.home-manager` accepts values shaped like `home-manager.lib.homeManagerConfiguration {}` ([your example](https://codeberg.org/Displace4490/sedlund-home/src/commit/af9c3547552f020cc04b2778f3e48104998f7770/flake.nix#L219)). I'm sure I didn't read the Home Manager Manual thoroughly enough, but I haven't seen any docs/mention of `homeManagerConfiguration` elsewhere.

**Comment by sedlund** [comment]
yeah its not well documented on the hm site.  there is a template that mentions it [here](https://github.com/nix-community/home-manager/blob/304a011325b7ac7b8c9950333cd215a7aa146b0e/templates/standalone/flake.nix) in the repo
