### ISSUE TITLE
Lix support

### ISSUE THREAD

**Issue by hauleth** [serokell/deploy-rs#288]
I have tried deploying machine where [Lix](https://lix.systems/) would be used as a Nix implementation. This results in activation hook timeout and I do not know how to proceed with the debugging it. I do not know if it is exactly bug in `deploy-rs` or Lix, but I would like to get some hints how I can debug it further.

**Comment by magneticflux-** [comment]
Was this between different versions of Lix and Nix? I've been using the same version of Lix (nightly) everywhere: on the send and receive side of `deploy-rs`, between remote builders, and with SSH substituters, and haven't had any issues.

**Comment by PhilTaken** [comment]
@hauleth do you have any specific issues? I have lix running on the local side and nix from nixos-unstable on all remotes without any issues

**Comment by hauleth** [comment]
After repeated applies it finally worked, so I am closing it, as it works as is currently.
