### ISSUE TITLE
Unable to override inputs

### ISSUE THREAD

**Issue by jcf** [serokell/deploy-rs#289]
I have a small project where I configure a number of my machines with Nix and would love to use deploy-rs to switch configurations. Unfortunately, I've run into a small issue.

When I run my tiny wrapper script that takes care of overriding inputs so devenv can find the current working directory without needing impurity, I run into what appears to be an argument parsing issue.

`bin/deploy`

``` sh
#!/usr/bin/env zsh
set -ex
cd "${0:h}/.."

target="${1:-.}"
shift

exec nix run github:serokell/deploy-rs "$target" -- \
  --override-input devenv-root "file+file://"<(printf %s "$PWD") \
  "$@"
```

Invoking `bin/deploy .#max-vm` results in the following:

```
➜ bin/deploy .#max-vm
+bin/deploy:3> cd bin/..
+bin/deploy:5> target='.#max-vm' 
+bin/deploy:6> shift
+bin/deploy:8> printf %s /Users/jcf/.config/setup
+bin/deploy:8> nix run github:serokell/deploy-rs '.#max-vm' -- --override-input devenv-root file+file:///dev/fd/12
error: Found argument '--override-input' which wasn't expected, or isn't valid in this context

If you tried to supply `--override-input` as a PATTERN use `-- --override-input`

USAGE:
    deploy <target>

For more information try --help
```

I am using an explicit target and `--` to separate out the `--override-input`.

Is this working as expected? I suppose overriding inputs might not be supported by design, and I could rip out devenv (although it's handy having language support in here as I have a lot of snippets of code in this repository I use to automate various tasks on my provisioned machines).

And thanks for sharing this awesome tool!

**Comment by PhilTaken** [comment]
Currently you are just passing the `--override-input` to deploy-rs, if you want to pass it to nix run you have to move it after `nix run`.

Additionally, github:serokell/deploy-rs has no input called devenv-root so I'm not sure what you're trying to accomplish with that.

Is the devenv-root input part of your flake?
