### ISSUE TITLE
documentation for checks outdated

### ISSUE THREAD

**Issue by ElliottSullingeFarrall** [serokell/deploy-rs#296]
I believe the documentation for implementing `checks` may be outdated.

I noticed that something like
```
inputs.deploy-rs.x86_64-linux.deployChecks inputs.self.deploy
```
is not a derivation but rather a set of 2 derivations, namely `deploy-schema` and `deploy-activate`, and so does not function as a check.

In my flake I have fixed this by using
```
(inputs.deploy-rs.x86_64-linux.deployChecks inputs.self.deploy).deploy-activate
```
and similarly for `deploy-schema`. This is similar to the approach used in snowfallorg/lib/issues/112

**Comment by PhilTaken** [comment]
> is not a derivation but rather a set of 2 derivations

what in the documentation implies otherwise? the readme specifies 

```
checks = builtins.mapAttrs (system: deployLib: deployLib.deployChecks self.deploy) deploy-rs.lib;
```

which works perfectly for the official flake schema (https://nixos.wiki/wiki/flakes)

```
# Executed by `nix flake check`
  checks."<system>"."<name>" = derivation;
```

**Comment by ElliottSullingeFarrall** [comment]
My apologies, you're absolutely right. I was struggling to get it working with snowfall-lib but  that was my misunderstanding. Got it working now.
