### ISSUE TITLE
[Question] remoteBuild has no effect, still build locally.

### ISSUE THREAD

**Issue by amalgame21** [serokell/deploy-rs#300]
I used `remoteBuild = true;` but it still build on local machine.
same as `--remote-build` flag.
I configure the flake like this:

```nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-24.05";
    deploy-rs.url = "github:serokell/deploy-rs";
  };
  outputs = { self, nixpkgs, deploy-rs, ... } @ inputs: {
    nixosConfigurations = {
      remotelaptop = nixpkgs.lib.nixosSystem {
        # ...
      };
      # ...
    };

    deploy.nodes = {
      "remotelaptop" = {
        hostname = "l"; # hostname in ~/.ssh/config
        interactiveSudo = true;
        remoteBuild = true;
        profiles.system = {
          user = "root";
          sshUser = "normaluser";
          path = deploy-rs.lib.x86_64-linux.activate.nixos self.nixosConfigurations."nixos-desktop";
        };
      };
    };
    # This is highly advised, and will prevent many possible mistakes
    checks = builtins.mapAttrs (system: deployLib: deployLib.deployChecks self.deploy) deploy-rs.lib;
  };
}
```

I am very new to deploy-rs, this is the first deploy system I use after I switch to nixos.
Usually I just ssh into the remote system and run `nixos-rebuild switch`, which is quite demanding.
I have no experience to deploy remote machine like this, even the `nixos-rebuild --target-host --build-host` command (Not using it because it seem not supporting sudo with password)
Does it require some additional settings like `nix.settings.trusted-user` ? Thanks!

**Comment by amalgame21** [comment]
Seems it is caused by the `nixpkgs.hostPlatform` and `nixpkgs.buildPlatform`

https://github.com/serokell/deploy-rs/issues/200#issuecomment-1523352787

deploy-rs is so hard to use imho, documentation seems incomplete.

**Comment by nikp123** [comment]
> deploy-rs is so hard to use imho, documentation seems incomplete.

I know this is off-topic: But have you found any alternatives. NixOps just seems deprecated, and the other solutions don't seem that popular.
