### ISSUE TITLE
Is it possible, when deploying 1 host, to only fetch the stuff for that specific host?

### ISSUE THREAD

**Issue by bbigras** [serokell/deploy-rs#37]
If I run `deploy .#laptop` on my laptop, it will also fetch everything that my desktop needs.

**Comment by notgne2** [comment]
By default, deploy-rs will run `nix flake check` (or a similar stable-Nix alternative) before deploying, you can disable this with `--skip-checks`, I guess this may be a reason to rethink that decision

**Comment by notgne2** [comment]
The evaluation step will probably also end up fetching useless things, even with `--skip-checks`, #63 should fix that!

**Comment by notgne2** [comment]
I'm closing this now as #63 has merged, and the full evaluation step is intentional (and can be skipped with `--skip-checks`). If it still happens regardless then this should be re-opened.
