### ISSUE TITLE
rollback even if I got "Success activating!"

### ISSUE THREAD

**Issue by bbigras** [serokell/deploy-rs#38]
I'm pretty sure I'm seeing a rollback even if I got "Success activating!".

Is there a log or something on the target to verify?

EDIT: I see 2 `hm-activate-bbigras` runs for the same deploy.

**Comment by bbigras** [comment]
Here's a recording of it. I'm running it on my desktop (target is desktop too). The deploy is done at 01:38.

[![asciicast](https://asciinema.org/a/tDTskWPC83UERbFIUdS1F2Cnr.svg)](https://asciinema.org/a/tDTskWPC83UERbFIUdS1F2Cnr)

**Comment by bbigras** [comment]
Here's a recording with some of the journalctl output:

[![asciicast](https://asciinema.org/a/cWyezNGsjm2mGg9nYu4AqrUu3.svg)](https://asciinema.org/a/cWyezNGsjm2mGg9nYu4AqrUu3)

**Comment by kalbasit** [comment]
I'm having the same problem. A workaround is to deploy without the magic rollback:

```
deploy --magic-rollback false .#host
```

**Comment by notgne2** [comment]
@kalbasit that helps narrow down the issue too, I'm assuming that the magic-rollback forked process is somehow unable to detect the "confirmation file" that gets produced to let that process know that the system is still functional and able to accept connections

**Comment by notgne2** [comment]
I'm going to add an option which makes that process log to a file (it obviously can't log to stdout as it has to outlive the SSH connection), that way I can see what is going wrong. It's been configured to be extremely "cautious", if it encounters any error at all waiting for the confirmation file it will roll back (the preferable alternative to a bad config + a bad error leaving your machine potentially broken/inaccessible).

**Comment by szlend** [comment]
I'm not sure if this is related but I see a lot of hanged activation scripts running on my server. Some of them are consuming 100% of CPU, like they're stuck on something.

**Comment by bbigras** [comment]
> I'm not sure if this is related but I see a lot of hanged activation scripts running on my server. Some of them are consuming 100% of CPU, like they're stuck on something.

Did you see https://github.com/serokell/deploy-rs/issues/32 @szlend ?

**Comment by antifuchs** [comment]
I'm seeing the same thing happen on my aarch64-linux machine. From what I can tell, one magic-rollback activation binary gets run; that terminates correctly and deploy success is announced. Then, *another* activation binary seems to get started (forked from somewhere?) which doesn't seem to be able to detect success & performs a rollback to the previous version.

I've started `kill -9`ing that second activate process, but that requires some pretty snappy timing on my part /:

**Comment by antifuchs** [comment]
Hrm, so I think this may be tied to the change in #29 - suspect the file watcher is looking at the wrong file.

I have a change in https://github.com/serokell/deploy-rs/compare/master...antifuchs:confirm-via-socket (which isn't working yet) that changes the whole thing around, so the confirmation program listens on a unix domain socket, and the confirmation step connects to it (via an `activate-rs` subcommand), confirming that we're set.

**Comment by notgne2** [comment]
Can anybody replicate this issue still now that https://github.com/serokell/deploy-rs/pull/40 has merged?

**Comment by bbigras** [comment]
I did 1 deploy and it went fine. I will continue to test in the next days.

The new log format looks nice.

**Comment by antifuchs** [comment]
I did a test deploy on master, and that also didn't get automatically rolled back. Seems good to me!

**Comment by antifuchs** [comment]
One thing that I noticed after a (correctly) failed deploy is that the local deploy-rs control program had exited, but ssh to the target system was still streaming messages. That was a bit surprising, and I suspect it'd be better if the deploy program waited until the watchdog program's ssh terminal exited. Otherwise, a huge improvement in both reliability & understandability.

**Comment by notgne2** [comment]
@antifuchs I've created #49 for that now
