### ISSUE TITLE
Show profiles before deploying them

### ISSUE THREAD

**Issue by balsoft** [serokell/deploy-rs#4]
Sometimes it would be nice to see what's going to happen before `deploy-rs` starts doing its work. In particular, I propose to add a generic `interactive :: boolean` attribute to the deploy attrs, and if it is set to `true` for a profile, `deploy-rs` dumps the fully evaluated  profile to stdout/stderr (in pretty-printed JSON/YAML/TOML, doesn't really matter here but it should be human-readable) and interactively asks the user to confirm the deployment. A very nice feature would be to also consider _where_ the generic setting was specified, and ask before doing anything for that particular level (i.e. if `interactive = true` for a node, dump all profiles that are to be deployed for that node and ask before deploying anything for that node).

Example of desired behavior:
```
$ nix run github:serokell/deploy-rs -- .#foo.system --interactive
 INFO  deploy > Running checks for flake in .
warning: unknown flake output 'deploy'
 INFO  deploy > Evaluating flake in .
 INFO  deploy > The following profiles for flake . are to be deployed:
 foo:
   system:
     user: root
     path: /nix/store/...-nixos-system-foo-20.09pre-git
     hostname: foo.example.com
     interactive: true
     sshOpts:
       - "-p"
       - "1234"
 INFO  deploy > Are you sure you want to deploy those profiles? (only the word yes is accepted)
 ? yes
 INFO  deploy::utils::push > Building profile `system` for node `foo`
<...>
```

```
$ nix run github:serokell/deploy-rs -- .#foo --interactive
 INFO  deploy > Running checks for flake in .
warning: unknown flake output 'deploy'
 INFO  deploy > Evaluating flake in .
 INFO  deploy > The following profiles for flake . are to be deployed:
 foo:
   system:
     user: root
     path: /nix/store/...-nixos-system-foo-20.09pre-git
     hostname: foo.example.com
     interactive: true
     sshOpts:
       - "-p"
       - "1234"
   home-manager:
     user: vasya
     path: /nix/store/...-home-manager-generation-vasya
     hostname: foo.example.com
     interactive: true
     sshOpts:
       - "-p"
       - "1234"
 INFO  deploy > Are you sure you want to deploy those profiles? (only the word yes is accepted)
 ? yes
 INFO  deploy::utils::push > Building profile `system` for node `foo`
<...>
```

**Comment by mkaito** [comment]
How about a `--dry-run` option? You know, do everything up to but not including actually touching the servers.

**Comment by balsoft** [comment]
Yeah, that would be a nice addition, but for now you can just pass `--interactive` and say `no` after being asked about it.
