### ISSUE TITLE
Activation preset for home-manager

### ISSUE THREAD

**Issue by notgne2** [serokell/deploy-rs#43]
Despite intentionally remaining profile-agnostic, deploy-rs provides support for NixOS in the form of `activate.nixos`, I would like to provide a similar option for home-manager deployments, this is something I know to be possible as I use it in my own deployments, though last time I checked required modifying some of home-manager's code.

**Comment by Pacman99** [comment]
It would be great if you could share the code for how to do this. I don't entirely know how to use the custom activate script, so I wasn't able to figure it out myself.
And what would you have to modify in home-manager?

**Comment by notgne2** [comment]
I don't actually remember the modifications I made, the original file which I copied and altered has changed quite some bit (and I think the way I made it work was not entirely correct anyway). I'm going to revisit how to do it from scratch, and document it as I go.

**Comment by notgne2** [comment]
So it looks like the issue is that `modules/modules.nix` will try to use `<nixpkgs>` unless you call it with `useNixpkgsModule = false;`, which makes sense, and it would be as simple as providing this flag, _but_, the ways home-manager exports itself for usage is through `homeManagerConfiguration` in the flake, which uses `modules/default.nix` internally, or simply using `modules/default.nix`, but `modules/default.nix` actually doesn't let you change all the arguments given to `modules/modules.nix`.

My modified code was simply a `modules/default.nix` altere to call `modules/modules.nix` with `useNixpkgsModule = false;`

It looks like the actual NixOS module (`nixos/default.nix`) actually completely skips over `modules/default.nix` entirely, making it perhaps less insane for me to include (a better version of) my altered code in deploy-rs, though it still seems like a design oversight on home-manager's part, and might be worth taking upstream.

**Comment by notgne2** [comment]
There's also a little bit of philosphical design consideration to be done, for the NixOS activation it makes a lot of sense, you use `nixpkgs.lib.nixosSystem`, and give that to `activate.nixos` which turns it into a deploy path for deploy-rs. `home-manager` has no such method (it has `homeManagerConfiguration`, which is exactly that, but is for our purposes, completely broken), so we would have to make our activation helper take the config and system, then do all the generation internally, which seems very weird

**Comment by notgne2** [comment]
Thankfully, I now believe I am an idiot, and everything I have just said seems to be wrong. Adding `inherit pkgs; useNixpkgsModule = false;` to `extraSpecialArgs` seems to fix everything, guess I forgot my way around the module system

**Comment by notgne2** [comment]
So basically, something like this _does_ seem to work
```nix
        {
          profiles.notgne2-home-manager = {
            user = "notgne2";
            profilePath = "/nix/var/nix/profiles/per-user/notgne2/home-manager";
            path = deploy-rs.lib.${system}.activate.custom (home-manager.lib.homeManagerConfiguration {
              inherit pkgs system;
              extraSpecialArgs = { inherit pkgs inputs; };
              homeDirectory = "/home/notgne2";
              username = "notgne2";
              configuration = ./home-manager/configuration.nix;
            }).activationPackage "$PROFILE/activate";
          };
        }
```

And if we add a preset for it, it can look like this

```nix
        {
          profiles.notgne2-home-manager = {
            user = "notgne2";
            profilePath = "/nix/var/nix/profiles/per-user/notgne2/home-manager";
            path = deploy-rs.lib.${system}.activate.hm (home-manager.lib.homeManagerConfiguration {
              inherit pkgs system;
              extraSpecialArgs = { inherit pkgs inputs; };
              homeDirectory = "/home/notgne2";
              username = "notgne2";
              configuration = ./home-manager/configuration.nix;
            });
          };
        }
```

I'm still not sure why it works, or why it didn't, but I don't think that matters too much
