### ISSUE TITLE
Don't quit until SSH connections are closed

### ISSUE THREAD

**Issue by notgne2** [serokell/deploy-rs#49]
The current behaviour allows `deploy` to quit due to errors while leaving SSH connections open, printing messages while the program is closed and you have returned to your shell. The excess of logs is nice, though it is not very good looking, we should hold `deploy` open until these connections no longer exist

**Comment by stevenroose** [comment]
Yeah I'm getting errors and deploy never seems to exit. It hangs and when I

- press enter, I get the SSH key passphrase prompt
- ctrl-c it exits.
