### ISSUE TITLE
Question about multiple profiles

### ISSUE THREAD

**Issue by bbigras** [serokell/deploy-rs#51]
> This type of design (as opposed to more traditional tools like NixOps or morph) allows for lesser-privileged deployments, and the ability to update different things independently of eachother. You can deploy any type of profile to any user, not just a NixOS profile to root.

If I have a system profile for my server with nginx set up. Is it possible to deploy another profile that would set another vhost for nginx (`services.nginx.virtualHosts`)?

I'm guessing it can't be done and multiple profiles are more for things that wouldn't have to modify the configuration.nix file.

**Comment by notgne2** [comment]
I think for reasons beyond the scope of deploy-rs, using NixOS modules in a non-system profile is unlikely to work, NixOS probably won't appreciate existing twice.

Also, I think what you are describing also involves many more changes to nixpkgs for the nginx module to integrate in that way.

I'll have some better examples of using multiple profiles soon (including deploying home-manager separately), but basically deploying NixOS consists of setting the system profile using `nix-env` (which updates `/nix/var/nix/profiles/system`), and running `sudo /nix/var/nix/profiles/system/bin/switch-to-configuration switch`. deploy-rs just also makes it possible for you to deploy a different profile other than system, and run an activation script other than `switch-to-configuration switch`, with a user other than `root`.

Within Serokell, this is commonly used to deploy our own services from CI/CD so no root access to nodes is needed, just access to a user account which deploy-rs will use to deploy the service.

**Comment by bbigras** [comment]
Yeah, I think I was just confused by the "deploy things independently" thing. Thanks.
