### ISSUE TITLE
Command-line syntax for deploying multiple specific node/profile paths

### ISSUE THREAD

**Issue by stevenroose** [serokell/deploy-rs#60]
This can be a bundle of features

-[ ] Allow to specify one or more nodes to deploy, f.e. `--node staging --node production`
-[ ] Allow a node to be excluded from the default if no flags are set, f.e. `defaultDeploy = false;` so that it has to be deployed with an explicit --node

**Comment by notgne2** [comment]
We already support specifying a node to deploy (`deploy .#my-computer`) and specifying what profile of it too (`deploy .#my-computer.myuser-home-manager`). There's no way to do multiple, but I think we could re-use this same argument format but allow it to be specified multiple times. `defaultDeploy` does seem like a good feature to have though.

**Comment by felixscheinost** [comment]
+1 on deploying multiple nodes , in parallel if possible

Flake evaluation is quite slow on my machine for some reason so maybe reusing the evaluated flake and/or deploying nodes in parallel would be a great feature IMO.

**Comment by notgne2** [comment]
Parallel is #46 , so I guess this issue should now refer to a command-line syntax to deploy multiple specific paths at once, as in something similar to

`deploy .#my-computer .#my-other-computer .#yet-another-computer.system`

instead of just

`deploy .` or `deploy .#my-computer`

**Comment by ysndr** [comment]
#80 implemented if anyone would like to verify and approve it.
