### ISSUE TITLE
Activate is trying connect with wrong user name

### ISSUE THREAD

**Issue by Zhevlovd** [serokell/deploy-rs#61]
I deploy the flake:
`
{
  description = "Deployment for my servers";
  inputs = {
    deploy-rs.url = "github:serokell/deploy-rs";
    nixpkgs.url = "github:NixOS/nixpkgs/release-20.09";
  };

  outputs = { self, nixpkgs, deploy-rs }: {

    nixosConfigurations = {
      nixos-test = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        modules = [ ./nixos-test/configuration.nix ];
      };
    };

    deploy = {
      magicRollback = false;
      autoRollback = true;
      nodes = {
        nixos-test = {
          hostname = "192.168.122.107";
          profiles = {
            system = {
              user = "root";
              sshUser = "dz";
              fastConnection = false;
              path = deploy-rs.lib.x86_64-linux.activate.nixos self.nixosConfigurations.nixos-test;
            };
          };
        };
      };
    };
    checks = builtins.mapAttrs (system: deployLib: deployLib.deployChecks self.deploy) deploy-rs.lib;
  };
}
`
Build and "nix copy" steps are running fine. But Activate step is trying to connect with username "ssh".

**Comment by notgne2** [comment]
Should be fixed now, though out of curiousity, on what OS/environment did you experience this?

**Comment by Zhevlovd** [comment]
I use Linux Mint 19.3 and local installed nix.
$ uname --all
Linux dz-desktop 5.4.0-66-generic #74~18.04.2-Ubuntu SMP Fri Feb 5 11:17:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ nix --version
nix (Nix) 2.4pre20201205_a5d85d0
