### ISSUE TITLE
Infinite Recursion Encountered

### ISSUE THREAD

**Issue by ericbmerritt** [serokell/deploy-rs#73]
I get the following error when running deploy-rs. I ended up pulling down the example to see what I was doing wrong and I am still getting this. I am a bit stuck. 

`nix run github:serokell/deploy-rs -- . -- --impure --show-trace
🚀 ℹ️ [deploy] [INFO] Running checks for flake in .
warning: Git tree '/home/eric/workspace/foobar' is dirty
warning: unknown flake output 'deploy'
🚀 ℹ️ [deploy] [INFO] Evaluating flake in .
warning: Git tree '/home/eric/workspace/foobar' is dirty
error: --- EvalError ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
infinite recursion encountered
------------------------------------------------------------------------------------------------ show-trace ------------------------------------------------------------------------------------------------
trace: while evaluating the attribute 'text' of the derivation 'deploy.json'
at: (7:7) in file: /nix/store/sdjxjsd5phr225rs2qzklj2xci0c9gr0-source/pkgs/build-support/trivial-builders.nix

     6|     stdenv.mkDerivation ({
     7|       name = lib.strings.sanitizeDerivationName name;
      |       ^
     8|       inherit buildCommand;

trace: while evaluating the attribute 'buildCommand' of the derivation 'jsonschema-deploy-system'
at: (7:7) in file: /nix/store/sdjxjsd5phr225rs2qzklj2xci0c9gr0-source/pkgs/build-support/trivial-builders.nix

     6|     stdenv.mkDerivation ({
     7|       name = lib.strings.sanitizeDerivationName name;
      |       ^
     8|       inherit buildCommand;

🚀 ❌ [deploy] [ERROR] Failed to evaluate deployment data: Evaluation resulted in a bad exit code: Some(1)`

**Comment by notgne2** [comment]
Is this with one of the provided examples? Both seem to work fine for me. Either way that's an interesting log, the error seems related to the jsonschema check provided in `deployChecks.schema` (and utilized in a flake when adding `checks = builtins.mapAttrs (system: deployLib: deployLib.deployChecks self.deploy) deploy-rs.lib;`), but it appears checks have already completed and succeeded, and the evaluation step shouldn't need them (and in newer deploy-rs versions even has restricted evaluation and only cares about what is in `deploy`).

**Comment by ericbmerritt** [comment]
I went to create a minimal reproduction of this problem and I can no longer repro it. That makes me nervous, but I am going to close this as non-reproducible.
