### ISSUE TITLE
bootstrapping

### ISSUE THREAD

**Issue by blaggacao** [serokell/deploy-rs#74]
How to bootstrap a deploy-rs remote host?

We need a blessed path to it.

- My journey: https://github.com/divnix/devos/issues/167 (stuck with `/mnt` subdir on the live cd)
- Other approaches: https://github.com/divnix/devos/issues/132#issuecomment-799016542 &rarr; https://github.com/Xe/nixos-configs/blob/ec73a55b42836ef194a38c8bad5a938e11f3b979/hosts/lufta/bootstrap.nix

**Comment by blaggacao** [comment]
I see this in the examples: https://github.com/serokell/deploy-rs/blob/master/examples/system/bare.nix

@notgne2 Do you think it is worth exploring a more generalized and standard approach or is direction to leave that concern to the users? At any rate, I'll try to adopt the approach in `bare.nix` downstream and see where it leads me to.

I was wondering if it is desirable to provide a more wired-up solution that builds when doing `deploy bootstrap` or something similar.

**Comment by blaggacao** [comment]
Closing as https://github.com/serokell/deploy-rs/issues/75#issuecomment-799821923 is a sufficient solution.

**Comment by balsoft** [comment]
> I see this in the examples: https://github.com/serokell/deploy-rs/blob/master/examples/system/bare.nix

Please note that the examples were copied from https://github.com/serokell/deploy/tree/master/examples without modification, so some of it might be strange or even not work.

> How to bootstrap a deploy-rs remote host?

> We need a blessed path to it.

I'm not sure I understand the question. deploy-rs assumes that a remote host is already running some sort of a NixOS installation. Do you mean we should add a way to deploy to a remote subdirectory, like from a NixOS installation ISO? That would be nice, but it would require quite a lot of changes to the code, and there are a lot of edge cases there to be thought about (e.g. where and how to install the bootloader).

**Comment by blaggacao** [comment]
I yesterday implemented a couple of things in `divnix/devos`. They are documented here: https://devos.divnix.com/doc/start/bootstrapping.html

It would be nice if we could keep on spinning the yarn to make the overall bootstrapping experience as versatile as possible.

**Comment by balsoft** [comment]
Ok, would you mind opening an issue about that?
