### ISSUE TITLE
Configurable file permissions for tempPath

### ISSUE THREAD

**Issue by notgne2** [serokell/deploy-rs#8]
Once this is added, we can safely make it default to `777` alongside the default path being `/tmp/deploy-rs` fixing issues with user profiles deploying after system profiles running into permission errors.

**Comment by mkaito** [comment]
Is there a reason it isn't just 777 by default anyway?

Also, why not key the canary with a hash of the node and profile names, so each thing gets its own?

**Comment by notgne2** [comment]
> Is there a reason it isn't just 777 by default anyway?

Because the path is configurable, and sometimes 777 would be inappropriate

> Also, why not key the canary with a hash of the node and profile names, so each thing gets its own?

This is already the case, just the hashed directories go inside of `tempPath` to not be messy, and if it does not already exist, right now it gets created with the default umask causing other users to not be able to touch it.

**Comment by mkaito** [comment]
> This is already the case

If this was the case, we wouldn't be seeing an error. That's why I say to also hash the profile name. Maybe even the user. The point is to not get a collision when different users deploy different things.

**Comment by notgne2** [comment]
There is no collision. If you manually do `mkdir /tmp/deploy-rs && chmod 777 /tmp/deploy-rs` you will deploy everything without errors (until you reboot) as all of the deploy-rs confirmation files will be in `/tmp/deploy-rs/${narHash}/confirm` (or something like that), the issue is if `/tmp/deploy-rs` doesn't already exist, `deploy-rs` will have to create that too, with of course the default permissions, which breaks it for other users.

The alternative would be doing something like `/tmp/deploy-rs-${narHash}/confirm`, but I consider this much uglier

**Comment by mkaito** [comment]
I don't think using a flat namespace is ugly at all. I would actually use `/tmp/deploy-rs-${narHash}-confirm`.

**Comment by notgne2** [comment]
I th

**Comment by notgne2** [comment]
I don't think you can have it fully flat as inotify needs to watch a directory

**Comment by notgne2** [comment]
Actually I think I'm wrong, because it's a file being deleted not the other way round that can work

**Comment by mkaito** [comment]
You need to watch the parent folder when watching for files being created, but otherwise you can watch files themselves.
