### ISSUE TITLE
deploy-rs-deps fails to build on aarch64-linux (emulated by x86_64-linux)

### ISSUE THREAD

**Issue by cmacrae** [serokell/deploy-rs#88]
👋 

I'm encountering an issue when trying to set up my Raspberry Pi 4 system for deployment using deploy-rs.  
Currently, my flake is set up such that:  
- `deploy` is being run from a darwin system
- Remote builders for aarch64-linux systems are configured
- These remote builders are actually x86_64-linux systems with `boot.binfmt.emulatedSystems = [ "aarch64-linux" ];` set

Deploying my x86_64-linux systems configuration from the darwin system works fine.  
Attempts at deploying the aarch64-linux system configuration is building in the correct environment (QEMU on the various x86_64-linux systems).

However, it seems it fails to build the `deploy-rs-deps` derivation each time.  
Initially it seemed quite consistent that it was failing to compile `rnix`, however I see now that it is the same result for `regex` - so it seems it could be failing to build several dependencies, with the exact same error.

I'm not really sure how to debug this, I'm afraid.  
Please do let me know if there's any further information I can provide to help narrow this down.

#### Build log
```
unpacking sources
unpacking source archive /nix/store/zzjp1hmhwqf2adwn3iwc9vapiv5w7hvb-dummy-src
source root is dummy-src
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
[naersk] cargo_version (read): 1.51.0
[naersk] cargo_message_format (set): json-diagnostic-rendered-ansi
[naersk] cargo_release: --release
[naersk] cargo_options: -Z unstable-options
[naersk] cargo_build_options: $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
[naersk] cargo_test_options: $cargo_release -j "$NIX_BUILD_CORES"
[naersk] RUST_TEST_THREADS: 4
[naersk] cargo_bins_jq_filter: .
[naersk] cargo_build_output_json (created): /build/tmp.0VG62DVXzw
[naersk] crate_sources: /nix/store/cl0rwwqrijbx5rwaahhmp43fwcqdzsxh-crates-io
[naersk] RUSTFLAGS: 
[naersk] CARGO_BUILD_RUSTFLAGS: 
[naersk] CARGO_BUILD_RUSTFLAGS (updated): --remap-path-prefix /nix/store/cl0rwwqrijbx5rwaahhmp43fwcqdzsxh-crates-io=/sources
building
cargo -Z unstable-options build $cargo_release -j "$NIX_BUILD_CORES" --out-dir out --message-format=$cargo_message_format
   Compiling proc-macro2 v1.0.24
   Compiling libc v0.2.81
   Compiling autocfg v1.0.1
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.54
   Compiling version_check v0.9.2
   Compiling cfg-if v0.1.10
   Compiling log v0.4.11
   Compiling lazy_static v1.4.0
   Compiling memchr v2.3.4
   Compiling cfg-if v1.0.0
   Compiling slab v0.4.2
   Compiling serde_derive v1.0.118
   Compiling bitflags v1.2.1
   Compiling serde v1.0.118
   Compiling proc-macro-hack v0.5.19
   Compiling maybe-uninit v2.0.0
   Compiling ryu v1.0.5
   Compiling proc-macro-nested v0.1.6
   Compiling smallvec v1.5.1
   Compiling scopeguard v1.1.0
   Compiling unicode-segmentation v1.7.1
   Compiling rustc-hash v1.1.0
   Compiling hashbrown v0.9.1
   Compiling smol_str v0.1.16
   Compiling lazycell v1.3.0
   Compiling serde_json v1.0.60
   Compiling same-file v1.0.6
   Compiling once_cell v1.5.2
   Compiling text_unit v0.1.10
   Compiling futures-core v0.3.8
   Compiling unicode-width v0.1.8
   Compiling thin-dst v1.1.0
   Compiling regex-syntax v0.6.21
   Compiling glob v0.3.0
   Compiling os_str_bytes v2.4.0
   Compiling yansi v0.5.0
   Compiling itoa v0.4.6
   Compiling deploy-rs v0.1.0 (/build/dummy-src)
   Compiling bytes v0.6.0
   Compiling pin-project-lite v0.2.0
   Compiling pin-utils v0.1.0
   Compiling termcolor v1.1.2
   Compiling anymap v0.12.1
   Compiling strsim v0.10.0
   Compiling vec_map v0.8.2
   Compiling whoami v0.9.0
   Compiling yn v0.1.1
   Compiling num-traits v0.2.14
   Compiling num-integer v0.1.44
   Compiling crossbeam-utils v0.7.2
   Compiling indexmap v1.6.0
   Compiling tokio v0.3.5
   Compiling thread_local v1.0.1
   Compiling instant v0.1.9
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling lock_api v0.4.2
   Compiling heck v0.3.1
   Compiling walkdir v2.3.1
   Compiling futures-task v0.3.8
   Compiling textwrap v0.12.1
   Compiling rowan v0.9.1
   Compiling quote v1.0.7
   Compiling iovec v0.1.4
   Compiling net2 v0.2.37
   Compiling parking_lot_core v0.8.1
   Compiling signal-hook-registry v1.3.0
   Compiling time v0.1.44
   Compiling inotify-sys v0.1.4
   Compiling atty v0.2.14
   Compiling num_cpus v1.13.0
   Compiling filetime v0.2.13
   Compiling fork v0.1.18
   Compiling mio v0.7.6
   Compiling aho-corasick v0.7.15
   Compiling mio v0.6.23
   Compiling parking_lot v0.11.1
   Compiling signal-hook v0.3.1
   Compiling inotify v0.8.3
   Compiling crossbeam-channel v0.4.4
   Compiling cbitset v0.2.0
   Compiling regex v1.4.2
   Compiling mio-extras v2.0.6
   Compiling rnix v0.8.0
   Compiling chrono v0.4.19
   Compiling notify v5.0.0-pre.4
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
error: could not compile `regex`

Caused by:
  process didn't exit successfully: `/nix/store/vcjiph4a5zvjksv947145pwv5f2qb0h0-rustc-1.51.0/bin/rustc --crate-name regex /nix/store/cl0rwwqrijbx5rwaahhmp43fwcqdzsxh-crates-io/regex-1.4.2/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="aho-corasick"' --cfg 'feature="default"' --cfg 'feature="memchr"' --cfg 'feature="perf"' --cfg 'feature="perf-cache"' --cfg 'feature="perf-dfa"' --cfg 'feature="perf-inline"' --cfg 'feature="perf-literal"' --cfg 'feature="std"' --cfg 'feature="thread_local"' --cfg 'feature="unicode"' --cfg 'feature="unicode-age"' --cfg 'feature="unicode-bool"' --cfg 'feature="unicode-case"' --cfg 'feature="unicode-gencat"' --cfg 'feature="unicode-perl"' --cfg 'feature="unicode-script"' --cfg 'feature="unicode-segment"' -C metadata=53f1767719c2c331 -C extra-filename=-53f1767719c2c331 --out-dir /build/dummy-src/target/release/deps -L dependency=/build/dummy-src/target/release/deps --extern aho_corasick=/build/dummy-src/target/release/deps/libaho_corasick-3b02d2684b1ac6ae.rmeta --extern memchr=/build/dummy-src/target/release/deps/libmemchr-14a2050e43ae83c2.rmeta --extern regex_syntax=/build/dummy-src/target/release/deps/libregex_syntax-606aecb5da33a214.rmeta --extern thread_local=/build/dummy-src/target/release/deps/libthread_local-4087a19f3b0d7674.rmeta --cap-lints allow --remap-path-prefix /nix/store/cl0rwwqrijbx5rwaahhmp43fwcqdzsxh-crates-io=/sources` (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
error: build failed
[naersk] cargo returned with exit code 101, exiting
builder for '/nix/store/fmwkkyppmjjbgb1wh1cf2r9w21vwzjbz-deploy-rs-deps-0.1.0.drv' failed with exit code 101
```

**Comment by notgne2** [comment]
That's interesting, I assume the deployment works succesfully if you don't install deploy-rs on the remote machine? Does `nix build github:serokell/deploy-rs#defaultPackage.aarch64-linux` on a machine with the builders configured or the builders themselves also fail? Also if possible can you test installing/compiling deploy-rs on one of the `aarch64-linux` machines?

**Comment by notgne2** [comment]
Oh I guess I was forgetting that the `activate` binary has to exist on the target machine too so it will be necessary for all deployments. I'm trying to run the build now with my own emulated aarch64-linux system (I don't have a real one) so I'll see if I run into similar issues

**Comment by notgne2** [comment]
Looks like I get no such issues when building it myself on a remote builder with aarch64-linux emulation, searching up that qemu error does seem to suggest that updating qemu might help, so maybe you could try bumping nixpkgs on your remote builder

**Comment by cmacrae** [comment]
Thanks for investigating @notgne2 🙇 Hmm, weird - I'm seeing this issue on `nixpkgs-unstable` rev `3eac120c3d228289f218c2db971849c39202e7f4`  

It's still consistently failing. I'll try a build on the actual aarch64 machine and see where I get

**Comment by cmacrae** [comment]
So, I wasn't able to use my actual aarch64 system to test the build - it's the DNS/DHCP server for my network and any heavy workloads take down my network 😅 However, I quickly set up [this automated build](https://github.com/cmacrae/deploy-rs-aarch64-builds/runs/2588407639?check_suite_focus=true) and it worked absolutely fine.  

No idea why my 3 x86_64 NixOS systems are failing in the same manner to build it 😕 But it's clearly an issue with my systems. So, I'll close this off!

Thanks for your help on this @notgne2 🙇

**Comment by cmacrae** [comment]
@notgne2 Whilst I wasn't able to ascertain the (unrelated) root cause of my issue, I was able to implement what I feel is a nice work around for it: [provide an automated build pipeline with a binary cache](https://github.com/cmacrae/deploy-rs-binary-builds).

The [pipeline I put together](https://github.com/cmacrae/deploy-rs-binary-builds/blob/master/.github/workflows/build.yaml) builds for x86_64-linux, x86_64-darwin, and aarch64-linux (all the systems I use deploy-rs on).  

Is this something you guys would be interested in inheriting? Or perhaps it's something you already provide - I see @yegortimoshenko has [a Serokell cache](https://app.cachix.org/cache/serokell) set up already.

If it is something you'd be interested in, I'll happily contribute a PR :)
